### ISSUE TITLE
AddOn: Statusbericht

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/friendsofredaxo.github.io#105]
Ausgabe eines Statusberichtes der aktuellen REDAXO Installation

Welche AddoOns sind installiert (aktiv,inaktiv, Version (mögliche Version))
Welche Themes, Module sind installiert.

Quasi ein erweiterter Systembericht...

**Comment by staabm** [comment]
mit welchem ziel? warum braucht man das? wie ist der use-case?

**Comment by olien** [comment]
Aktuell machen wir so etwas für die schlimmste WP Installation aller Zeiten.
Wir Dokumentieren welche Dingen in welcher Version installiert sind (und warum).
Dies ist die Grundlage für weitere Arbeiten...

**Comment by alexplusde** [comment]
Feature für das Projekt Manager Add-on imho

**Comment by olien** [comment]
stimmt. da passt es rein..
