### ISSUE TITLE
Info für Redakteure, dass es Updates gibt (als "Hinweis Addon?)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/friendsofredaxo.github.io#106]
Sollten natürlich irgendwie konfigurierbar sein falls der Admin beschliesst ein AddOn nie updaten zu wollen...

![image](https://user-images.githubusercontent.com/330516/58456681-1b1a6b00-8125-11e9-8cbe-0f025b25c29f.png)

Soweit ich gehört habe ist der Entwickler verpflichtet, dem Betreiber der Seite darauf hinzuweisen, dass er dafür sorgen muß, dass das System "sicher" (und somit aktuell?) bleibt.

**Comment by eaCe** [comment]
Das würde zu https://github.com/FriendsOfREDAXO/minibar/issues/31 passen

**Comment by alexplusde** [comment]
Ich sehe da Raum und Platz für ein generelles notification center

**Comment by olien** [comment]
Ja. Fänd ich auch gut. Evtl. losgelöst von anderen Addons

**Comment by olien** [comment]
Sollen wir Ideen sammeln?

Hinweis bei:
* Updates
* Fehler im Log
...

**Comment by alexplusde** [comment]
Admin an Redakteure, Admin an alle, Admin an Gruppen, cronjob, System-Log, Warnung für veraltete PHP-Version, FOR-Mitteilungen optional (also News aus der Community)

Ich sehe gedanklich vor mir das, was man bei Google mit der Benachrichtigungsglocke kennt oder unter Facebook.

Features einer Benachrichtigung: Text, call-to-action Button (z.b. jetzt updaten, ...)

**Comment by eaCe** [comment]
Generell fände ich es gut wenn Entwickler einfach via API Notifications triggern können.
Etwa:

```php
rex_message::error('Mein Fehler');
rex_message::warning('Meine Warning');
rex_message::info('Meine Info');
```

**Comment by alexplusde** [comment]
Wäre gut. Mir wäre hingegen wichtig, dass Meldungen an verschiedene Benutzer rausgehen können und somit auch einzeln gelesen und protokolliert werden können.

**Comment by alxndr-w** [comment]
Kann über das Project Manager Add-on erzielt werden. Das listet mögliche Updates.
