### ISSUE TITLE
Ruby Anleitung für Linux. 

### ISSUE THREAD

**Issue by crydotsnake** [FriendsOfREDAXO/friendsofredaxo.github.io#117]
Hallo!, Ich wollte fragen ob es sinnvoll eine Anleitung hinzuzufügen, wie man Ruby unter Ubuntu installieren kann! 😊. In der SETUP.md.

**Comment by schuer** [comment]
Gerne, @crydotsnake!

**Comment by crydotsnake** [comment]
Okay :blush:. Spätestens morgen abend ist der PR da :). @schuer

**Comment by crydotsnake** [comment]
Hier komme ich aktuell nicht weiter.. nach dem Befehl `gem install bundler:1.16.1'
 Kommt das:

![Bildschirmfoto vom 2020-02-22 14-40-40](https://user-images.githubusercontent.com/39345336/75093380-67de8580-5581-11ea-99c5-d9966a06b3bc.png)

Und wenn ich das Paket installieren will was er möchte, kommt das:

![Bildschirmfoto vom 2020-02-22 14-43-50](https://user-images.githubusercontent.com/39345336/75093412-c1df4b00-5581-11ea-9b92-c4004ac5040c.png)

**Comment by crydotsnake** [comment]
Hättest du vllt eine Idee?.. @bloep

**Comment by schuer** [comment]
Ich kenne mich mit Ubuntu leider wenig aus, @crydotsnake, aber bei den Tricks hatte schonmal jemand die SETUP.md mit Linux-Infos ergänzt: https://github.com/FriendsOfREDAXO/tricks/blob/master/SETUP.md
Vielleicht hilft das auch an dieser Stelle.

**Comment by crydotsnake** [comment]
Nein, leider nicht..

**Comment by alxndr-w** [comment]
Darf ich hier schließen?
