### ISSUE TITLE
Addons archivieren - Vorgehensweise

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/friendsofredaxo.github.io#119]
* Bevor das Repo archiviert wird, überprüfen, ob PRs offen sind und deren Autoren informieren: Aus Höflichkeit.
* Ein Issue "Dieses Addon wird nicht mehr gewartet." erstellen und pinnen.
* In der README.md darauf hinweisen und ggf. eine Alternative empfehlen.
* In der Repo-Beschreibung schreiben "Dieses Addon wird nicht mehr gewartet" und ggf. eine Alternative empfehlen
* Im Installer die Beschreibung anpassen und darauf hinweisen, dass dieses Addon nicht mehr gewartet wird und ggf. eine Alternative empfehlen.

Anschließend das Addon-Repository archivieren.

**Comment by alxndr-w** [comment]
Offene Issues als "wontfix" taggen und schließen als "nicht geplant"

**Comment by eaCe** [comment]
Man kann diese nur normal schließen, wenn man nicht jedes einzeln öffnen möchte. Zumindest meine ich das
![grafik](https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io/assets/2708231/5fe44933-95cb-48bf-b1eb-d2e1e397152f)
