### ISSUE TITLE
Teams bilden, um diese in Issues anpingen zu können

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/friendsofredaxo.github.io#120]
Wäre es sinnvoll bei FOR Teams zu bilden?

- PHP
- Javascript
- Docs
- ...

Damit könnte man dann die Teams direkt anpingen und so eine spezielle Gruppe mit Leuten erreichen die sich dann das Problem annehmen können.

Beispiel hier
https://github.com/FriendsOfREDAXO/redactor/issues/20

Ich überlegte grad, wer für das "Problem" (Javascript) in Frage käme. Ich hätte jetzt einzelne aufzählen können, weiß aber nicht ob sie überhaupt JS gern machen. Andere Nichtaufgezählte geht das runter wie Öl und toben sich gern in JS aus.

Ein Ping an eine Gruppe würde da einiges erleichtern und man erreicht die "Experten" auf deren Gebiet.

**Comment by alexplusde** [comment]
Finde ich eine gute Idee. Müssten halt auch entsprechende Leute bereitstehen und sich angesprochen fühlen.

**Comment by schuer** [comment]
Gute Idee! Ich habe mal Teams angelegt, so dass wir damit rumspielen können:
https://github.com/orgs/FriendsOfREDAXO/teams

Pings funktionieren dann so:

@FriendsOfREDAXO/css 
@FriendsOfREDAXO/js 
@FriendsOfREDAXO/php 

Jetzt müssen sich nur noch die Leute in die entsprechenden Teams hinzufügen.
