### ISSUE TITLE
Addon: Advanced Backups

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/friendsofredaxo.github.io#19]
Vielleicht kennt jemand von euch auch dieses sehr gute Backup-Plugin für Wordpress:
https://de.wordpress.org/plugins/backwpup/

Feature-Liste:

```
Datenbank-Backup (benötigt mysqli)
WordPress XML Export
Erzeuge eine Datei, die die installierten Plugins enthält
Datenbank optimieren
Datenbank überprüfen und reparieren
Datei(en)-Backup
Backups im Dateiformat zip, tar, tar.gz, tar.bz2 (benötigt gz, bz2, ZipArchive)
Datensicherung in einem Verzeichnis ablegen
Datensicherung an einen FTP-Server senden (benötigt ftp)
Datensicherung in die Dropbox legen (benötigt curl)
Datensicherung zu S3-Dienstleistern (benötigt PHP 5.3.3, benötigt curl)
Datensicherung zu Microsoft Azure (Blob) (benötigt PHP 5.3.2, curl)
Datensicherung zu RackSpaceCloud (benötigt PHP 5.3.2, curl)
Datensicherung zu SugarSync (benötigt curl)
PRO: Datensicherung auf Amazon Glacier (benötigt PHP 5.3.3, curl)
PRO: Datensicherung auf Google Drive (benötigt PHP 5.3.3 und curl)
Logs und Backup per E-Mail verschicken
```

Besonders positiv hervorzuheben ist das Datei-Backup, dass die Skript-Limits umgeht und so auch Backups von mehreren Gigabyte an Daten machen kann - und diese eben extern speichert.

So etwas vermisse ich für Redaxo.

**Comment by schuer** [comment]
@VIEWSION ist neu bei FOR (Willkommen!) und möchte sich evtl. um das Projekt kümmern.

**Comment by VIEWSION** [comment]
ok... weit weit entfernet von dem was das Wordpress Plugin macht, aber für machen vielleicht hilfreich:  https://github.com/FriendsOfREDAXO/export_cleanup - die kleine Erweiterung sorgt dafür dass bei häufigen automatischen Backups der Webspace nicht vorläuft....
