### ISSUE TITLE
Diskussion: Wie veröffentlichen wir Inhalte auf redaxo.org?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/friendsofredaxo.github.io#2]
Ich fände es gut, wenn alle Beteiligten eigenständig (natürlich in Absprache) Projekte auf redaxo.org veröffentlichen könnten, und nicht nur wenige einzelne mit Zugriffsrechten.

Wollen wir für myREDAXO einen neuen Account für FOR anlegen? Und wenn ja, wie handhaben wir das mit dem Passwort? Vielleicht schlicht im Wiki hinterlegen und alle paar Monate mal ändern?

Oder gibt es grundsätzlich eine bessere Idee fürs Veröffentlichen?

**Comment by staabm** [comment]
Von welcher Art von Inhalten sprichst du? Für dokumentation o.ä. könnte ich mir auch gut vorstellen das ganze via github zu realisieren und aus redaxo.org dann die inhalte via github api abzuholen.

wg. addon releases: sehr cool wäre, wenn wir einen webhook hätten der erkennt, wenn ein neues release auf github getagged wird und dieses dann via myredaxo zur verfügung steht (wie es composer und packagist macht)

**Comment by gharlan** [comment]
Ich denke @schuer geht es hier jetzt speziell um die gemeinsam entwickelten Addons.

> wg. addon releases: sehr cool wäre, wenn wir einen webhook hätten der erkennt, wenn ein neues release auf github getagged wird und dieses dann via myredaxo zur verfügung steht (wie es composer und packagist macht)

Fände ich auch gut!

> Wollen wir für myREDAXO einen neuen Account für FOR anlegen? Und wenn ja, wie handhaben wir das mit dem Passwort? Vielleicht schlicht im Wiki hinterlegen und alle paar Monate mal ändern?

Ein gemeinsamer Account dafür fände ich auch gut. Passwort im Wiki hinterlegen finde ich sehr problematisch. Dann kann ja jeder sehr leicht mit dem Passwort im Namen der FOR Schadcode hochladen, der sich dann rasch verbreiten könnte (da die Leute FOR vertrauen, und das Update rasch runterladen).

**Comment by staabm** [comment]
wenn wir es via webhook von github aus machen würden, bräuchte niemand das pw zum redaxo.org account von FOR kennen und die admins würden den webhook einmalig in einem repos konfigurieren.

**Comment by gharlan** [comment]
Jupp, deswegen fände ich speziell hier den Weg über die GitHub Releases sehr sinnvoll.
Aber auch allgemein fände ich es mittlerweile gut.

**Comment by schuer** [comment]
Cool, klingt gut! Könnt ihr das machen?

**Comment by staabm** [comment]
ich denke einen webhook einzurichten wäre nicht schwierig
https://developer.github.com/webhooks/creating/

einen github service-hook zu etablieren wäre langsfristig super
https://developer.github.com/webhooks/#service-hooks

den mechanismus von dem wir hier reden wäre ja generell für addons interessant die auf github entwickelt werden, auch außerhalb der FOR organisation.

**Comment by staabm** [comment]
das wäre vllt sogar ein todo was am redaxo tag in einer kleinen session programmiert werden könnte (auch wenn ich leider nicht dabei bin)

**Comment by schuer** [comment]
Gregor wird das vermutlich implementieren. Allerdings ist vorher noch etwas Abstimmung nötig, deshalb wird die Implementierung nicht so bald passieren.

Wir werden bis dahin manuell veröffentlichen, so wie bisher.

**Comment by schuer** [comment]
Inzwischen gibt es die Installer Action (https://github.com/FriendsOfREDAXO/installer-action), die neue Github-Releases automatisch im REDAXO-Installer veröffentlicht. Der notwendige Authenifizierungs-Token ist innerhalb der FOR-Organisation hinterlegt, so dass keine Zugangsdaten mehr zwischen den Leuten hin- und hergetauscht werden müssen.
