### ISSUE TITLE
Addon: QuickCreate

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/friendsofredaxo.github.io#22]
Stellt überall einen "NEU"-Button zur Verfügung. Der Button fungiert als Shortcut, indem man mit einem Klick zum Ziel kommt.
## Use Case
- Sowohl Redakteure, als auch Entwickler werden in einer Vielzahl der Fälle - insb. bei der Einrichtung des Systems - ständig damit konfrontiert, neue Inhalte zu erstellen. Dabei muss man sich immer wieder durch die Struktur oder Addon-Seiten kämpfen.
- Darüber hinaus fällt es einigen Redakteuren schwer, sich zu merken, wie man einen neuen Artikel oder eine neue Kategorie erstellt. In einigen Fällen wird eine Kategorie erstellt, obwohl der Redakteur einen Artikel erstellen möchte und vice versa. 

Für diese Fälle würde sich der QuickCreate-Button anbieten.
## Features
- Es lassen sich von Haus aus direkt neue Artikel, Kategorien, Media Manager-Profile, Sprachen, Templates, Module, etc. erstellen
- Über Extension Points können sich Addons einklinken, bspw.
  - Meta Infos
  - Cronjob
  - YForm-Table Manager - direkt einen neuen Datensatz erstellen, bspw. News, Termin, Produkt, ...
  - YRewrite - neue Domain erstellen
  - etc.
- Es werden nur Einträge angezeigt, für die der Nutzer die entspr. Berechtigung hat

![image](https://cloud.githubusercontent.com/assets/3855487/19173113/efdd512e-8c25-11e6-824f-f490fc62bf70.png)

**Comment by staabm** [comment]
Die idee finde ich cool. 

Man müsste schauen wieviel/welche einträge dort alle rein müssen um das richtige ui control dafuer zu benutzen

**Comment by alexplusde** [comment]
ein Mega Menu ;)

**Comment by olien** [comment]
Kann das nicht mit Watson gemacht werden? @tbaddade

**Comment by tbaddade** [comment]
@olien Ja kann man. Man kann sogar die Inputs/Textarea via Watson befüllen.

**Comment by alexplusde** [comment]
Dann könnte man das ja u.U. in Watson integrieren? @tbaddade 

Ich finde, Watson nutzen eh viel zu wenige (mich miteingeschlossen. Ich vergesse immer, dass es das gibt :D)

**Comment by staabm** [comment]
Für mich könnte das auch ein core feature sein.

**Comment by alexplusde** [comment]
Hier geht's weiter: https://github.com/redaxo/redaxo/issues/1156
