### ISSUE TITLE
Github organization page

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/friendsofredaxo.github.io#24]
Hey,

jetzt wo FOR immer aktiver wird und eine große Zahl von Projekten enthält, könnten wir mal eine Github-Page einrichten, die einen Überblick der Projekte auflistet, vielleicht nach Anzahl der Stars sortiert. Mit Screenshot und kurzer Projektbeschreibung.

Damit hätten Interessierte — und wir selbst — einen besseren Überblick darüber, was FOR bietet und wie es sich entwickelt.

Nicht?

* https://help.github.com/categories/github-pages-basics/
* https://help.github.com/categories/customizing-github-pages/

**Comment by staabm** [comment]
finde ich eine super idee. mit gh-pages wie vorgeschlagen lässt sich das ja auch super gut machen.

**Comment by tbaddade** [comment]
> man könnte in diesem "Info" repos mit einem gh-pages branch arbeiten

Finde ich am sinnvollsten, da das Info Repo die erste Anlaufstelle für Informationen rund um FOR ist

**Comment by schuer** [comment]
Zwei Beispiele für Organization pages, die ihre Repos listen:

* http://shopify.github.io
* http://esri.github.io

**Comment by schuer** [comment]
Auf der Page könnten wir übrigens auch die Summe aller Stars ausgeben lassen, und bei jedem Meilenstein (z. B. 50, 100, 200, 500…) feiern wir ein REDAXO-Fest 🥇

**Comment by alexplusde** [comment]
Bin gespannt, wie das für FOR aussieht :)

**Comment by schuer** [comment]
> > man könnte in diesem "Info" repos mit einem gh-pages branch arbeiten

> Finde ich am sinnvollsten, da das Info Repo die erste Anlaufstelle für Informationen rund um FOR ist

@tbaddade @staabm: Ein `gh-pages`-Branch funktioniert nur bei Project Pages. Wir wollen aber eine Organization Page für FOR machen, deshalb geht nur das Schema, ein Repo zu erstellen mit dem Namen `friendsofredaxo.github.io` und darin im `master`-Branch zu arbeiten, siehe https://help.github.com/articles/user-organization-and-project-pages/

**Comment by schuer** [comment]
Ich habe es mal direkt angelegt, damit wir loslegen können:

Website: https://friendsofredaxo.github.io
Repo: https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io

Bisher besteht der Inhalt aus schlichtem Markdown. Den dynamischen Part, also die Auflistung der Repos samt Sortierung nach Stars usw. müssten wir bei Gelegenheit mal mit Jekyll bauen, siehe https://help.github.com/categories/customizing-github-pages/

**Comment by schuer** [comment]
Sorry, ich muss nochmal öffnen: Wollen wir die Gelegenheit nutzen, und das aktuelle `info`-Repo umbenennen in `friendsofredaxo.github.io`? Dann hätten wir alles an einer Stelle, und das war sicherlich die Motivation von @staabm und @tbaddade oben.

Was meint ihr?

**Comment by staabm** [comment]
👍

**Comment by schuer** [comment]
Okay, cool. Erledigt.

**Comment by alexplusde** [comment]
@schuer und wie werden da jetzt die Repos gefeatured?

**Comment by schuer** [comment]
@alexplusde Dafür muss man jetzt mittels Jekyll, einem Generator für statische Websites, eine entsprechende Website zusammenbauen. Github stellt Jekyll die notwendigen Daten zur Verfügung, siehe https://help.github.com/articles/repository-metadata-on-github-pages/.
