### ISSUE TITLE
Website: Build-Job einrichten

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/friendsofredaxo.github.io#29]
Aktuell wird die Website bei jedem Commit gebaut. Weil wir aber die Metadaten nutzen und anzeigen, wie viele Mitglieder wir sind, wie viele Stars vergeben wurden und eine Highscore ausgeben, sollten wir die Website regelmäßig automatisch bauen lassen, damit die Daten immer aktuell sind.

**Comment by schuer** [comment]
Falls jemand Lust hat, das einzurichten: sehr gerne! Ich müsste mich erstmal einlesen und habe in den nächsten Tagen nicht viel Zeit, käme also erst in einer Woche dazu.

**Comment by staabm** [comment]
wie würde man das genau machen? via travis cronjob?

**Comment by schuer** [comment]
Travis, ja. Wie genau, müsste ich auch erst lesen.

**Comment by staabm** [comment]
https://docs.travis-ci.com/user/cron-jobs/#Adding-Cron-Jobs

**Comment by staabm** [comment]
Hab ne travis config erzeugt und einen daily cron hinterlegt... d.h. Alle 24h müsste sich die seite nun aktualisieren (falls ich es nicht verrafft hab)

**Comment by staabm** [comment]
Hier ist noch bissl was dokumentiert bzgl travis und jekyll integration http://jekyllrb.com/docs/continuous-integration/travis-ci/

**Comment by schuer** [comment]
Sehr cool, danke @staabm!
Wollen wir den Cron nicht lieber 1h oder 2h setzen? Github hat ein Soft-Limit von 10 Builds pro Stunde, das sollte man sicherlich nicht ausreizen, aber nur alle 24h finde ich etwas wenig, oder?

**Comment by staabm** [comment]
Daily war der kürzeste auswählbare intervall.

Sobald jmd committed wird ja sowieso immer deployed wenn es kein error gibt.

**Comment by schuer** [comment]
Ah okay. Na perfekt, dann passt es ja.

**Comment by schuer** [comment]
Funktioniert leider noch nicht. Schauen wir uns nochmal an.

**Comment by schuer** [comment]
```
GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
GitHub Metadata: GET https://api.github.com/users/friendsofredaxo/repos?per_page=100&type=public: 403 - API rate limit exceeded for 54.87.185.35. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
```

https://travis-ci.org/FriendsOfREDAXO/friendsofredaxo.github.io/builds/196910478

**Comment by schuer** [comment]
Die Builds schlagen aktuell alle fehl, weil das API-Limit erreicht ist. Ich habe den Job deshalb vorerst deaktiviert, weil er sowieso noch nicht das macht, was wir wollen.

Grundsätzlich, um das mal hier zu notieren:
Travis baut das Projekt in seiner Umgebung und prüft, ob alles funktioniert wie es soll. Tut es nicht, weil Travis in die API-Limits von GitHub läuft. Das wiederum könnte man nun mittels Authentifizierung ermöglichen, allerdings passiert dann immer noch nicht das, was wir wollen, nämlich ein automatisches Update unserer Jekyll-Seite. Dafür müsste Travis entweder das gebaute Projekt gezielt zu GitHub zurückspielen, oder aber einen Commit absetzen, der GitHub anstößt, die Seite selbst zu bauen.

Wir werden eine Lösung finden — vermutlich eine der beiden genannten —, aber dafür müssen wir uns nochmal etwas Infos anlesen. Bis dahin updatet sich unsere FOR-Website nur dann, wenn wir irgendwas committen.

**Comment by staabm** [comment]
Api Auth sollten wir einrichten da aktuell ja auch die deployments bei regulären commits abbrechen, oder?

**Comment by schuer** [comment]
Der Build bei GitHub läuft eigentlich durch, weil hier die API-Limits nicht greifen. GitHub stellt der Jekyll-Config die Metadaten immer bereit. Auth benötigt man nur, wenn man den Job woanders laufen lassen will, also etwa lokal oder eben bei Travis.

Allerdings habe ich eben einen Commit abgesetzt, der ausgerechnet keinen Build ausgelöst hat. Keine Ahnung warum, aber es ist auch kein Fehler geflogen.

**Comment by schuer** [comment]
Gerade nochmal einen Test-Commit abgesetzt, und danach wurde unmittelbar gebaut.

**Comment by schuer** [comment]
Also, das Thema ist gar nicht so einfach. Es gibt verschiedene Lösungen, die darauf basieren, dass Travis baut und das Gebaute an Github zurückgibt. Aber das ist etwas Aufwand, und ich persönlich finde es robuster, wenn wir Github das Bauen überlassen.

Es gibt die Variante eines »Push ohne Commit«, den wir von Travis als Cron absetzen könnten. Das wäre vielleicht eine gute Option, weil sie das Commit-Log nicht unnötig befüllt. Dafür muss man Travis _nur_ die nötigen Rechte gewähren, pushen zu dürfen, und ein kleines Scriptlein bauen.
Mal sehen, wenn Zeit ist…

**Comment by schuer** [comment]
Und nochmal ein Schritt weiter: »Push ohne Commit« ist nicht mehr ohne weiteres möglich, weil die Gh-Pages für Organisationen im Master-Branch liegen, und der ist per Default gegen `push -f` geschützt. Und Push ohne Commit basiert auf `push -f`.

Man könnte den Schutz des Master-Branches aufheben, aber das halte ich nicht für sinnvoll, weil er dann ungeschützt wäre (und z. B. versehentlich gelöscht werden könnte), und weil die Prüfung durch Travis dann nicht mehr `required` ist, sondern quasi optional nebenher läuft.
— Das ginge alles, ist aber nicht schön.

Deshalb die Erkenntnis: Wenn wir ein Auto-Deployment per Cron wollen, müssen wir Travis committen lassen. Wir würden dann also täglich einen Commit in der History sehen, der auch entsprechende Alerts für FOR-Mitglieder wirft.
— Ich persönlich fände das okay. Was meint ihr?

**Comment by staabm** [comment]
Für dieses repos wäre ich ok mit einem force push. Ich vermute aber dass ein forcepush genauso notifications auslösen würde wie jeder normale commit, oder?

**Comment by tbaddade** [comment]
Meinetwegen könnte der Commit auch mehrmals am Tage laufen. Die Seite sollte aktuell sein und bleiben.

**Comment by schuer** [comment]
@staabm Ein force push würde keine Notifications schmeißen, glaube ich. Insofern eine schöne Lösung.
@tbaddade Travis’ Cron läuft nur alle 24 h, häufiger geht nicht. Wollten wir es häufiger, müssten wir einen anderen Dienst nehmen. Aber dann hätten wir mehrfach am Tag eine Commit-Message, das fände ich schon irgendwie störend. Einmal am Tag geht noch so gerade, nicht?

**Comment by staabm** [comment]
+1 für force-push, da das repos nicht sooo kritisch ist wie andere.

**Comment by schuer** [comment]
Hooray, wir haben nun ein tägliches Update per Cron :)

Ein kleiner Schönheitsfehler: Der force push feuert (wie in den verlinkten Artikeln beschrieben) zweimal. Erst wird der vorletzte Commit gepusht, danach der letzte/aktuelle, um den alten Zustand wiederherzustellen. **Und deshalb baut Travis im Anschluss leider auch zweimal.**
— Ist jetzt nicht wirklich schlimm, fordert nur unnötige Ressourcen bei Travis. Sorry :)

Jedenfalls: Läuft. I like.

**Comment by schuer** [comment]
Um nochmal zusammenzufassen, was jetzt eigentlich Sache ist:

* Die Website [friendsofredaxo.github.io](https://friendsofredaxo.github.io) aktualisiert sich **bei jedem Commit/Push** in den `master`-Branch. Immer, wenn jemand von uns eine Änderung macht — natürlich auch direkt über den Editor auf der Github-Weboberfläche —, ist diese also in <1 Minute live.
* Ein **Cron bei Travis** updated die Website einmal am Tag, unabhängig davon, wann zuletzt von uns geupdatet wurde. Zu welchem Zeitpunkt der Cron feuert, können wir nicht steuern. Aktuell passiert es etwa um 12:15 Uhr.
* Der `master`-Branch ist **nicht mehr protected**. Das darf er leider nicht sein, weil sonst `push --force` nicht funktionieren würde, die Aktion, die der Travis-Cron für das Website-Update verwendet.
* Jeder **PR wird von Travis geprüft**. Dauert etwa eine Minute, und diese Zeit sollten wir abwarten, bevor wir den PR mergen. Leider kann man die Prüfung nicht auf required setzen, weil der `master`-Branch nicht mehr protected ist.
* Wird ein **PR gemergt**, sorgt das für ein Update der Website.

**Comment by schuer** [comment]
Ich öffne nochmal, denn es gibt eine viel schönere Variante, einen Rebuild anzustoßen. Nämlich über die API: https://developer.github.com/v3/repos/pages/#request-a-page-build

Siehe auch https://developer.github.com/changes/2016-07-06-github-pages-preview-api/

```
curl "https://api.github.com/repos/github/developer.github.com/pages/builds" \
  -X POST
  -H 'Authorization: token TOKEN' \
  -H "Accept: application/vnd.github.mister-fantastic-preview" \
```

Toll, dass ich das nicht eher gesehen habe :-/

**Comment by schuer** [comment]
Okay, implementiert. Viel einfacher, und 2 Travis-Builds weniger.
Jetzt ist’s eine runde Sache.

**Comment by staabm** [comment]
Kann man den master jetzt wieder  protected setzen?

**Comment by schuer** [comment]
@staabm Ha ja, stimmt!
