### ISSUE TITLE
Info zur Vergabe der Versionsnummern in die Readme?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/friendsofredaxo.github.io#35]

**Comment by staabm** [comment]
einfach nur ein verweis auf semver, mehr nicht.. oder?

**Comment by tbaddade** [comment]
> einfach nur ein verweis auf semver, mehr nicht.. oder?

würde vermutlich reichen. Es sei denn, @schuer möchte noch ein paar Zeilen dazu notieren :)

Hier schonmal die Urls
http://semver.org/lang/de/
http://semver.org/lang/en/

**Comment by schuer** [comment]
Ich würde es kurz halten. Aber schon so, dass auch Leute es verstehen, die noch nie von Semver gehört haben und nicht von dem Thema erschlagen werden wollen.

**Comment by skerbis** [comment]
Ja. Ihr habt Recht. Soll ich es ändern?
