### ISSUE TITLE
Repos title als subline auf der website?

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/friendsofredaxo.github.io#40]
Damit man ausser dem namen noch ein bissl beschreibung hat. Die repos description ist ja normalerweise rel. Kurz.

Den text würde ich farblich so gestalten dass er im hintergrund steht und nicht zu sehr dominiert (auch in kleiner schrift)

**Comment by schuer** [comment]
Timing ;) Gerade #41 gemacht.

**Comment by schuer** [comment]
Achso, bei der Gelegenheit sollten wir mal einige Repo-Beschreibungen anpassen. Sowas wie »REDAXO 5 Addon - Redactor 2 Editor« ist nicht sonderlich hilfreich.

Ich kümmere mich drum…

**Comment by staabm** [comment]
Genau das gleiche gefühl hatte ich gerade als ich alle addon-title in der liste gesehen hab :-)

**Comment by schuer** [comment]
Repo-Beschreibungen einmal grundlegend angepasst. Wer Verbesserungen hat, gerne einwerfen!
