### ISSUE TITLE
Website: Github-Topics hinzufügen?

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/friendsofredaxo.github.io#42]
Sobald wir in den topics mal ordentlich gepflegte inhalte haben könnte man diese ggf. Auch auf der site anzeigen...

**Comment by schuer** [comment]
Ich habe die Befürchtung, dass es langsam etwas zu voll — und damit zu unübersichtlich — wird. Die Website hat ja die Absicht, alle FOR-Projekte übersichtlich darzustellen, und inzwischen nimmt sie immer mehr Funktionalität/Inhalt an.

Ich finde, wir haben inzwischen einen sehr schönen Stand erreicht, der für neue Nutzer:innen hoffentlich sehr nützlich ist. Aber wir sollten uns gut überlegen, was zukünftig noch ergänzt oder implementiert werden soll.

**Comment by staabm** [comment]
Sehe das ähnlich wie du, wollte es nur zur diskussion stellen

**Comment by schuer** [comment]
Beide dagegen und sonst kein weiteres Feedback, dann schließen wir doch hier vorerst?
Wer das Thema nochmal aufrollen möchte, kann ja gerne wieder öffnen.
