### ISSUE TITLE
Website: Empfehlungen zur Verwendung von Github-Topics anbringen?

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/friendsofredaxo.github.io#43]
Zur diskussion: möchten wir empfehlungen aussprechen wie github topics gepflegt werden könnten damit man die redaxo addons/resourcen besser auf githu findet?

Symfony hat sowas gemacht, mal als beispiel
http://symfony.com/blog/standardizing-the-github-topics-for-symfony-repositories

**Comment by schuer** [comment]
Finde ich gut, habe nur selbst wenig Lust auf das Thema. Wenn jemand mag, gerne!

**Comment by schuer** [comment]
Nach langer Zeit mal wieder dieses Issue gesehen und kurz beim verlinkten symfony-Artikel gelesen. Ich fände nun folgende Labels für FOR sinnvoll:

* `redaxo`, weil man damit gezielt nach REDAXO-Ressourcen suchen kann, auch wenn sie den Begriff nicht im Namen oder in der Beschreibung haben.
* `redaxo-addon`, weil man damit sehr gezielt Addons filtern kann und sieht, wie viele es gibt.

Was meint ihr?

**Comment by schuer** [comment]
Erledigt: `redaxo-addon` ergänzt, wo es noch fehlte, und eine Info in die README eingebracht.
Falls noch Diskussionsbedarf ist, gerne nochmal das Issue öffnen.
