### ISSUE TITLE
AddOn: Implementierung von 2-Faktor-Auth mittels Google Authenticator

### ISSUE THREAD

**Issue by Markus-GS** [FriendsOfREDAXO/friendsofredaxo.github.io#46]
Hallo,
hat einer von Euch vielleicht schon einmal mit dem Gedanken gespielt, ein Addon für GA zu "basteln"?

Sollte anhand dieser Klasse -> https://github.com/PHPGangsta/GoogleAuthenticator

gar nicht so schwer sein.

Würde ich im Zeitalter der andauernden Hackangriffe von überall als ein sinnvolles Projektchen ansehen.
Einsatzgebiet primär die Absicherung der Redaxo-Admin (bzw Super-Redakteur)-Konten

**Comment by bloep** [comment]
Ist dies überhaupt von seiten des Cores möglich?

**Comment by staabm** [comment]
Ich wüsste erstmal nicht was dagegen spricht.

Falls man diese themen jetzt angeht würd ich aber vermutlich erstmal webauth implementieren, da 2f über google auth schon bissl angestaubt ist

https://caniuse.com/#feat=webauthn

**Comment by bloep** [comment]
Ich würde ja in den Login-Prozess eingreifen wollen, sodass ein User erst als eingeloggt zählt, wenn 2 Factor bestätigt wurde. Dafür müsste ich den Login erweitern können oder nicht? Und ich sehe da keine Möglichkeit per `setFactoryClass` oder EPs einzugreifen...
@staabm wenn du mir auf die Sprünge helfen könntest wäre super.

**Comment by staabm** [comment]
Es gibt bisher keinen mechanismus um sich da via addon drannzuhängen.
Den backend login via rex-factory könnte da gut passen, müsste man aber erst bereitstellen.
Wenn man das mal prototypen würde, könnte man sich das dann genauer anschauen.

(Ich hatte das eher so verstanden als gäbe es kein „ok“ um sowas haben zu wollen.)

**Comment by bloep** [comment]
> (Ich hatte das eher so verstanden als gäbe es kein „ok“ um sowas haben zu wollen, das ist aber nicht der Fall.)

@staabm Sorry :wink: 
Das wäre auch meine Idee gewesen, den backend login mit rex_factory auszusatten oder EPs für zusätzliche Überprüfungen bereitzustellen.

**Comment by staabm** [comment]
> Sorry 😉

kein Grund sich zu entschuldigen. am besten du baust mal nen PR (ggf. sogar erstmal ohne addon sondern rein im core), dann sieht man am schnellsten was so nötig ist - falls du interesse daran hast.

**Comment by staabm** [comment]
rudimentär implementiert mit https://github.com/FriendsOfREDAXO/2factor_auth
