### ISSUE TITLE
Website: "Edit this page"

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/friendsofredaxo.github.io#48]
Einen edit this page button auf den FOR seiten, um einfach beitragen zu können

**Comment by staabm** [comment]
Sollte so gehen: `<a href="{{site.github.repository_url}}/blob/gh-pages/{{page.path}}">Edit this page</a>` müsste nur noch gestyled sein

**Comment by schuer** [comment]
In unserem Fall ist es der `master`-Branch, nicht `gh-pages`.
Aber ja, cool!

**Comment by schuer** [comment]
Anmerkung: Ich habe das Feature beim letzten großen PR nicht mit eingebaut. Aus verschiedenen Gründen:

* Wenn man den Link prominent anbringt, macht es die Seite merklich voller/komplexer. Bringt man ihn nicht sehr auffällig an, ist er wenig hilfreich.
* Editieren können nur FOR-Nutzer, und die kennen den Weg zu GitHub sowieso.

Ich würde dieses Feature nicht implementieren. Was meint ihr?
