### ISSUE TITLE
Website: Link in dieses Repo?

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/friendsofredaxo.github.io#49]
Wäre es eventuell auch noch sinnvoll, einen zentralen Link irgendwo zu platzieren, der hier ins Repo führt?

Auf der Startseite kann man theoretisch über das Repo in der Liste gehen, aber auf https://friendsofredaxo.github.io/info scheint es nicht so direkt einen Link zu geben.

**Comment by gharlan** [comment]
Oder auf https://github.com/FriendsOfREDAXO

**Comment by Hirbod** [comment]
oder die neue von mir gesponsorte Domain? friendsofredaxo.de ?

**Comment by schuer** [comment]
@Hirbod, ich mache mal ein neues Issue bzgl. der Domainnutzung auf.
