### ISSUE TITLE
Website: Verlinkung einzelner Abschnitte

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/friendsofredaxo.github.io#50]
Ich fände cool, wenn es auf https://friendsofredaxo.github.io/info die gleiche einfache Möglichkeit gäbe, einen Link direkt zu einem Abschnitt zu erstellen, wie auf https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io/blob/master/README.md
(Bei Hover über Überschriften erscheint links ein Link-Symbol.)

**Comment by schuer** [comment]
Ja, cool. Müssten wir dann nur per JS machen, weil Jekyll lediglich die README inkludiert.

**Comment by schuer** [comment]
Die IDs sind ja sogar schon drin. Dann ist es ja wirklich nur eine kleine Anpassung. Ich hatte befürchtet, wir müssten den Inhalt parsen und die IDs ergänzen.
