### ISSUE TITLE
Website: Suchfunktion/filter über die repositiories

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/friendsofredaxo.github.io#56]
Analog wie auf der repository übersicht hier auf github könnte auch die website eine javascript suche anbieten um die repository liste zu filtern

**Comment by schuer** [comment]
Ich persönlich würde das Feature nicht umsetzen. Es werden alle AddOns auf einer Seite ausgegeben, so dass man die Suche im Browser nutzen kann.
