### ISSUE TITLE
Kennzeichnung für Projekte, die noch in Arbeit/ohne Release sind?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/friendsofredaxo.github.io#57]
Thema im Slack eben:

> sollten wir addons irgendwie kennzeichnen, die noch nicht einsatzfähig sind? sei es, weil sie noch platzhalter sind, oder weil noch kein release existiert? inzwischen haben wir einige davon.  
und wenn ja, kennzeichnen. dann: wie?

> blog, piwik, lightgallery (?), articlelist (?), twoeg (?), webdav

> wie wäre es mit einem schicken icon? dann ist es nur ein zeichen.

Vorschläge:

* 🐣
* 🚨
* 📌
* 📎
* 🚧
* 🛡

Ich fände das Küken ganz oben passend :)

**Comment by staabm** [comment]
küken und baustelle find ich beide super

**Comment by polarpixel** [comment]
Andere Frage: Ist es überhaupt sinnvoll, schon ein Repo zu reservieren, wenn man erst einige Wochen oder Monate später Code hinzufügt? Diese Frage stelle ich mir z.B. grade mit einer Onepage-Demo.

**Comment by skerbis** [comment]
Wenn gemeinsam daran gearbeitet werden soll, aber das Konzept noch geklärt werden muss, wo willst du es sonst sammeln?

**Comment by polarpixel** [comment]
Ja, dann schon, klar. Ich meinte eher das reine Reservieren.

**Comment by alexplusde** [comment]
Man kann so zumindest schon mal Feature Requests anlegen.

**Comment by schuer** [comment]
Ich würde ein Repo reservieren, sobald der Plan steht, etwas ernsthaft zu bauen. Und wenn der Addon-Key beliebt sein könnte. Sowas wie `blog` zum Beispiel würde ich sehr frühzeitig sichern, während sowas wie `utzibutzi` auch erst kurz vor Abstimmung und Entwicklung angelegt werden könnte.

**Comment by schuer** [comment]
Zwischenstand: wollen wir 🐣?

**Comment by schuer** [comment]
Okay, mehrfach ja, keinmal nein. Deshalb habe ich das Küken mal eingesetzt:

webdav / @staabm 
blog / @staabm 
articlelist / @tgoellner 
piwik / @gseilheimer 
lightgallery / @gseilheimer 
twoeg / @tgoellner _(weil nur Alpha-Release bisher)_
mcalendar / @joachimdoerr 

Passt das? Sonst nehmt eure Küken wieder raus ;)

**Comment by staabm** [comment]
Finger weg von meinen kücken :-)

**Comment by skerbis** [comment]
die sind schon recht auffällig ;-)

**Comment by schuer** [comment]
Schon sehr auffällig, finde ich auch. Nicht gut?

**Comment by skerbis** [comment]
vielleicht eher an das Ende der Beschreibung

**Comment by staabm** [comment]
Finde es gut so

**Comment by schuer** [comment]
Auf der Website könnten wir es parsen und anders positionieren, aber auf Github nicht. Dort steht es einfach nur in der Repo-Description.

Ich finde es erstmal okay so, auch wenn es recht auffällig ist und mangels Markup eine genauere Beschreibung fehlt, wofür das Küken eigentlich steht.

**Comment by tbaddade** [comment]
Wie wäre es noch zusätzlich mit einem Topic "addon-küken" bei jedem AddOn.

**Comment by schuer** [comment]
Küken haben auf der Website nun einen erklärenden Title-Text. (Hier bei GitHub geht das natürlich nicht.)

**Comment by schuer** [comment]
Bleibt noch die Diskussion um Thomas’ Vorschlag, ein Topic `addon-küken` zu verwenden.
(Ich persönlich würde es nicht machen.)

**Comment by schuer** [comment]
Noch jemand zum Thema `addon-küken`? Sonst sollten wir vielleicht schließen…

**Comment by staabm** [comment]
+1 kein topic dafür

**Comment by schuer** [comment]
Okay, dann also close.
