### ISSUE TITLE
AddOn: News

### ISSUE THREAD

**Issue by tictactimon** [FriendsOfREDAXO/friendsofredaxo.github.io#63]
Hallo FOR-Community

Für meine Abschlussarbeit zur meiner Ausbildung als Mediamatiker/EFZ programmiere ich ein News AddOn für Redaxo 5. 
Das AddOn hat (momentan) zwei simple Funktionen:

- Automatische Installationen von Tabellen
- Installation von Ausgaben-Module (So wie das Formbuilder-Modul bei yform)

Da natürlich der OpenSource Gedanke nicht verloren gehen darf, will ich dieses AddOn euch zur Verfügung stellen damit ihr es später mit neuen Funktionen schmücken könnt. 

Weitere Funktionen wären z.B. 
- eigener URL Rewrite (Ausgabe findet nur in einem Artikel statt) 
- Rechte für Autoren
- Backup
- meta infos

Folgende AddOn's werden für dieses AddOn benötigt (welche auch von FOR sind, daher passt dieses AddOn gut in die Gruppe):
- redactor2
- mform
- yform

Der Name ist momentan: **vNews**
Da dieser Name fix ist darf er momentan noch nicht geändert werden, sobald meine Abschlussarbeit präsentiert wurde (mitte April) darf es gerne umbenannt werden. 

Info: Da es sich um eine Abschlussarbeit handelt, muss der Code zu 99% von mir stammen. Auf euer Hilfe wäre ich trotzdem angewiesen da ich an gewissen Punkte bei der AddOn Entwicklung sicher anstossen werde (Ist mein erstes AddOn). Hier werde ich mich via Slack melden. 

ich freue mich auf die Zusammenarbeit 👍

**Comment by schuer** [comment]
Spannend, @tictactimon.

Unter diesen Umständen brauchen/können wir ja auch gar nicht über den Namen und die möglichen Features diskutieren, sondern du legst am besten direkt los und richtest das Repo bei FOR ein. 😃 

Die Zugangsdaten zum myREDAXO schicke ich dir, damit kannst du schonmal den Addon-Key sichern.

**Comment by alexplusde** [comment]
Gibt's schon was zu sehen?

**Comment by tictactimon** [comment]
Unter https://github.com/tictactimon/vnews findet ihr die erste Beta. Testen und Verbesserungsvorschläge erwünscht 🙂

**Comment by schuer** [comment]
Hat es geklappt mit der Abschlussarbeit? Ist das Addon fertig geworden und hat bestanden?

**Comment by alexplusde** [comment]
Würde mich auch interessieren @tictactimon

**Comment by olien** [comment]
ping @tictactimon

**Comment by alexplusde** [comment]
Schade :(
