### ISSUE TITLE
AddOn: Hilfe (für Redakteure / Endkunden)

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/friendsofredaxo.github.io#64]
Ein Addon, das md-Dateien aus dem Data-Addon darstellt und dem Kunden einen Menüpunkt "Hilfe" zur Verfügung stellt. 

Quasi analog zum Doku-Plugin, jedoch mit dem Zweck, Endkunden eine Kurzanleitung zum System zu bieten und ggf. auf Eigenheiten in der Konfiguration einzugehen.

Features
- Lädt und parst md-Dateien aus dem Data-Verzeichnis. = updatefähig
- Eingabe von Screenshots, Videos und Links zum Backend  
- Vorlage mit Kurzanleitung für die wichtigsten Features
- Eingabe-Feld für Administratoren zum Hinterlegen von Kontaktdaten ("Bei Fragen wenden Sie sich an...") und Logo
- Das Addon kommt mit Dummy-Daten, die schon mal Struktur und Medienpool erklären.

**Comment by skerbis** [comment]
Zusätzlich: https://heelhook.github.io/chardin.js/

**Comment by olien** [comment]
Gute Idee. Ich hab vorgestern nach einem JS geguckt welches Tooltips bereitstellt. Vorgehensweise wäre - ähnlich wie bei sprog) eine CSS ID bzw. Klasse sowie einen Titel und die Beschreibung für den Tooltip anzugeben. Wenn die Daten wie bei Sprog editierter bleiben kann das auch individuell für Module / Addons erweitert werden.

**Comment by alexplusde** [comment]
@olien oder als data-Attribut, bspw. 

`data-rexhelp="Aktivieren Sie diese Option, um bla bla bla..."`

sollte aber auch touch-kompatibel sein.

**Comment by olien** [comment]
Hm. Dann kannst Du das aber nicht für vorhandene Elemente nutzen...

**Comment by skerbis** [comment]
Es sollte eine Mischung aus beidem sein. Default-Backend-Elemente müssten über einen Outputfilter beschrieben werden können und zusätzliche (z.B. in Modulen) über das DATA-Attribut.

**Comment by olien** [comment]
Beides geht locker via JS anhand der IDs / Klassen....

**Comment by olien** [comment]
https://github.com/christophboecker/help.php

**Comment by alexplusde** [comment]
Jop, da ist Christoph gerade dran auf Basis einer Vorlage von mir... komm da aber gerade auch nicht dazu, Feedback zu geben.
