### ISSUE TITLE
AddOn: Page Builder im Backend

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/friendsofredaxo.github.io#65]
_(Wie auch immer realsierbar)_

https://www.elegantthemes.com/plugins/divi-builder/
https://wordpress.org/plugins/siteorigin-panels/
https://wordpress.org/plugins/aqua-page-builder/screenshots/

Alle WP Plugins haben (für mich) den NAchteil, dass man im Backend nicht den Inhalt der einzelnen Elemente sehen kann...

LG
Oliver

**Comment by skerbis** [comment]
https://elementor.com

**Comment by skerbis** [comment]
Allerdings nutzen diese Lösungen den normalen Texteditor von Wordpress und misshandelt den. 
Die Lösungen sind nicht austauschbar. Sehr schlecht, wenn man sich für was besseres entscheiden will. 
Redaxo mit seinen Slices ist soweit besser und kann kompatibel gehalten werden. 
Eigentlich brauchen die Slices für sowas eine Wrapper-Ebene, die die Slices gruppiert. Die Slices benötigen dann noch Angaben zur Größe oder ähnliches. 

Eine andere Lösung wäre einfach eine Live-Preview des Frontends anzuzeigen, dann braucht man solche Spielereien nicht. (z.B. wie bei Sulu) 
![bildschirmfoto 2017-03-16 um 10 54 08](https://cloud.githubusercontent.com/assets/791247/23990607/e62cb0a4-0a36-11e7-809d-0629b3b866ad.png)

**Comment by skerbis** [comment]
Hier geht's weiter: https://github.com/FriendsOfREDAXO/frontend_edit

**Comment by olien** [comment]
Ähm.... Thomas? Das sind doch zwei vollkommen unterschiedliche Sachen. Es sei denn Du kannst später im Frontend auch die Grids und Module ändern... und nicht nur den Content bearbeiten...

**Comment by skerbis** [comment]
hab's umbenannt. Stimmt ist nur ein anderer Backend-View

**Comment by darwin26** [comment]
Hmmm,
aber dann wird das Block / Slices System von Redaxo komplett übern Haufen geworfen ...
oder eben ersetzt durch ein grid system mit diversen Tools (Ein/Ausgabe Module) zum Klicken/Drag&Drop'n

hmmm... @olien 
wie soll es aussehen?
oder reicht Dir ein automatisches Öffen/Schließen der Blöcke (container/rows/cols) egal was man als Block /Modul einfügt (Im Modul = Select/Auswahl der Spaltenbreite)? ...

was genau schwebt Dir da vor.

Gruß Christian

**Comment by alexplusde** [comment]
Würde es nicht reichen, einen Modus einzuführen, in der alle Blöcke standardmäßig im Bearbeiten-Modus gezeigt werden?

**Comment by olien** [comment]
Hey Christian,

dieses öffnen und schlissen von Blöchen wurd ja schon mehrfach realisiert (habe ich auch mal gemacht). So richtig fluffig ist das für einen Redakteur nicht.

Ich (muß) gerade eine WordPress Seite mit dem DIVI-Builder bauen. Klasse.
(Ist nur alles verloren wenn man DIVI mal nicht mehr nutzen mag / kann.)

So etwas wie hier: https://transfer.frontwise.com/frontwise/grid-editor/example/ fänd ich schon klasse!

( https://github.com/Frontwise/grid-editor )

LG
Oliver

**Comment by skerbis** [comment]
Entweder in SliceUi oder Blöcks (in den ganz frühen Versionen) gab es eine experimentelle Lösung und die Slices zu ordnen. Ich finde es gerade aber nicht. Der Ansatz war sehr smart. Man konnte die Slices in einem Grid anordnen.

**Comment by javanita** [comment]
https://github.com/eaCe/slice_ui

**Comment by skerbis** [comment]
Dann war's eine alte blöcks-Variante

**Comment by javanita** [comment]
Wenn ich das richtig sehe sind bei dem grid-editor nur RTE-Module drin. Aber schick ist das schon. Hat's schon einer ausprobiert?

**Comment by skerbis** [comment]
https://github.com/artf/grapesjs gerade entdeckt

**Comment by schuer** [comment]
Bricky, @olien? Kann dann hier geschlossen werden?
