### ISSUE TITLE
AddOn Idee: REXpixel - noch zeitgemäß?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/friendsofredaxo.github.io#66]
Hallo Zusammen, 

Für REDAXO 4 hatte ich das Addon REXpixel (https://github.com/olien/rexpixel) gebaut.

Inspiration war PerfectPixel:

https://www.youtube.com/watch?v=s9r9HlL-ShM

http://www.welldonecode.com/perfectpixel/

---

Ist so etwas in Zeiten der responsiven Webentwicklung noch sinnvoll? ( https://github.com/olien/rexpixel/issues/20 )

Lohnt es sich das für REDAXO 5 zu veröffentlichen?

LG
Oliver
(P.S.: Wie die meisten meiner Addons habe ich das nie benutzt :-))

**Comment by phoebusryan** [comment]
ich habe nicht mal gewusst, dass es sowas gibt. ich nutze perfectpixel als browseraddon. auch noch zu zeiten wo responsive design standard ist. sehe aber nicht wirklich einen grund für ein rex-addon :)

**Comment by olien** [comment]
Naja. Der Grund wäre das überall (Browserunabhängig) zur Verfügung zu haben aber danke für deine Meinung!

**Comment by schuer** [comment]
Ich habe das noch nie gemacht, Designs über eine Website gelegt, um zu vergleichen. Weil ich es nicht wichtig finde, pixel-perfekt zu sein. Mein Kollege hingegen arbeitet sehr penibel nach Vorgaben und hat bei der späteren QA durch die Kunden/Auftraggeber schon oft davon profitiert.

Insofern: Gibt wie so oft unterschiedliche Meinungen. Aber ich persönlich werde das Addon ganz bestimmt nicht benutzen ;)

**Comment by schuer** [comment]
Achso, aber unabhängig von den persönlichen Vorlieben: Ich finde, sowas sollte nicht Teil eines CMS' sein. Wenn man es unbedingt haben will, dann wirklich als Browser-Addon oder andere Wege.

**Comment by olien** [comment]
Ok. Solche Aussagen (dich ich unterschreibe) habe ich erwartet. Also mache ich den Deckel hier zu.
Danke!
