### ISSUE TITLE
AddOn: Finde ein AddOn von allen REDAXO Instanzen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/friendsofredaxo.github.io#70]
Hintergrund : Instagram funktioniert aktuell im YFeed AddOn nicht. Wenn das Update draußen ist sollte man es aktualisieren. Nur in welchen Projekten hat man das im Einsatz?

Eine Lösung wäre:
- AddOn erstellen, welches die Projekte und deren Datenbankverbindungen aufnimmt.
- Über die DB kann man auf die rex_config-Tabelle zugreifen und somit an die installierten AddOns herankommen.
- Ähnlich wie im Installer werden alle AddOns gelistet und dazu die Projekte in denen das AddOn aktiviert ist.
- Zusätzliche sollten auch eigene AddOns gelistet werden, die nicht auf redaxo.org hinterlegt (und so nicht im Installer zur Verfügung stehen) sind.
- Eine Liste mit allen Projekten und deren AddOns sowie zusätzliche Infos ob Aktualisierungen verfügbar sind.

**Comment by staabm** [comment]
ggf. wäre das auch als feature von redaxo.org interessant, dass man dort sieht welche webseiten/redaxo-instanzen man alle hat und welche addons in welchen versionen diese verwenden

(sowas wie ein redaxo instanz dashboard)

**Comment by skerbis** [comment]
Idee: Alternativ könnte der Installer in REDAXO per cron job prüfen ob relevante Updates vorliegen und den Admin informieren ggf. per E-Mail oder gesammelt via  redaxo.org an die Agentur über eine Api. Vorteil: in Redaxo.org müssen zunächst keine Daten erfasst werden.  Es sollte aber aus meiner Sicht nur für „sehr“ wichtige Updates sein.

**Comment by tbaddade** [comment]
Mir geht es nicht nur um Updates. Manchmal suche ich auch einfach ein AddOn welches in irgendeiner unserer Projekte verwendet wurde, welches auf redaxo.org aber nicht registriert ist.

**Comment by alexplusde** [comment]
Ich möchte das gerade in Angriff nehmen. Wir haben das Problem weniger mit veralteten Addon-Installationen, als auch mit Installationen, die einfach über die Zeit gewartet werden sollten oder wir Kunden auf Updates ansprechen wollen.

https://github.com/alexplusde/hello

**Comment by alxndr-w** [comment]
Es gibt dafür das Project Manager Add-on, da kann man das überprüfen.
