### ISSUE TITLE
Aufgaben Addon... Hat wer Lust das weiter voran zu treiben?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/friendsofredaxo.github.io#71]
Ich habe aktuell dafür leider keine Zeit…

**Comment by olien** [comment]
06.17 BST & BSB - Allgemeine Ladezeiten verbessern

**Comment by tbaddade** [comment]
> Hat sich gerade erledigt

Inwiefern?

**Comment by skerbis** [comment]
Ich mache daraus ein Praktikantenprojekt und hoffe auf Unterstützung für unseren Einsteiger ;-)

**Comment by tbaddade** [comment]
Super 👍
