### ISSUE TITLE
AddOn: Cookie-Law

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/friendsofredaxo.github.io#72]
Geht um diese Einblendung, dass man Cookies akzeptieren soll.

Bsp. Library: https://cookieconsent.insites.com

Der Text könnte mit einem Platzhalter `{{ cookie.text }}` versehen werden, der dann wiederum vom Sprog AddOn in die korrekte Sprache übersetzt wird.

**Comment by olien** [comment]
Ich nutze immer das hier:  https://www.primebox.co.uk/projects/jquery-cookiebar/

**Comment by alexplusde** [comment]
Wir haben uns selbst eins gebastelt, den ganzen sch*** bei cookieconsent.insites.com braucht keiner und einen backlink fügen sie standardmäßig auch ungefragt ein.

**Comment by tbaddade** [comment]
> und einen backlink fügen sie standardmäßig auch ungefragt ein.

@alexplusde Wo passiert das? Finde da nix.

Was auch immer hier passiert, ob was Eigenes oder irgendeine Library, dass AddOn selbst fände ich praktisch.

@alexplusde Magst das nicht übernehmen, wenn ihr schon was habt?

**Comment by alexplusde** [comment]
@tbaddade wenn du mir etwas Zeit lässt? Ich schreib dir mal in Slack.

**Comment by tbaddade** [comment]
> wenn du mir etwas Zeit lässt?

@alexplusde **Wir** lassen dir genug Zeit :)

**Comment by olien** [comment]
Würde so etwas nicht reichen?

```
<div id="cookieNotice">
  <span>Diese Webseite verwendet Cookies. Durch die Nutzung der Webseite stimmen Sie der Verwendung von Cookies zu.</span> <a href="/wDeutsch/datenschutz">Datenschutzinformationen</a>
  <span id="cookieNoticeCloser" style="display:none" onclick="document.cookie = 'hideCookieNotice=1;path=/;expires=Fri, 31 Dec 9999 23:59:59 GMT';jQuery('#cookieNotice').slideUp()">[x]</span>
</div>

<script>
  if(document.cookie.indexOf('hideCookieNotice=1') != -1){
    jQuery('#cookieNotice').hide();
  }
  else{
    jQuery('#cookieNotice').prependTo('body');
    jQuery('#cookieNoticeCloser').show();
  }
</script>

<style>
  #cookieNotice              {position:relative;background-color:#c0c0c0;border-bottom:solid 1px #a0a0a0;padding:10px;text-align:center}
  #cookieNoticeCloser        {color:transparent;position:absolute;right:10px;width:15px;height:15px;cursor:pointer}
  #cookieNoticeCloser:before {content:'';position:absolute;width:1px;height:9px;background-color:#000000;left:7px;top:3px;transform:rotate(-45deg);-webkit-transform:rotate(-45deg);}
  #cookieNoticeCloser:after  {content:'';position:absolute;width:1px;height:9px;background-color:#000000;left:7px;top:3px;transform:rotate(45deg);-webkit-transform:rotate(45deg);}
</style>
```

**Comment by schuer** [comment]
@olien Die Implementierung ist kein Problem. Ich denke, es geht Thomas vor allem darum, dass die Texte innerhalb von REDAXO gepflegt werden können.

**Comment by olien** [comment]
@schuer Das ist mir schon klar. Ich wollte wissen ob so ein einfaches Script nicht reichen würde...

**Comment by alexplusde** [comment]
Ich finde, wenn ich einen weiteren Tag darüber nachdenke, dass das mit `global_settings` von @RexDude und einem händischen Einpflegen einer CSS + JS-Datei eigentlich getan ist.

https://github.com/RexDude/global_settings

**Comment by skerbis** [comment]
Ein AddOn dazu ist gerade in Arbeit

**Comment by staabm** [comment]
brauchts dafür wirklich ein addon? das ist in 10 zeilen js/css/html gelöst ohne ein addon oder sonstwas?

**Comment by skerbis** [comment]
Abwarten

**Comment by alexplusde** [comment]
statt abwarten: Was ist denn geplant?

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/cookie_consent

**Comment by staabm** [comment]
hier gehts weiter https://github.com/FriendsOfREDAXO/cookie_consent
