### ISSUE TITLE
AddOn: Ein oder zwei Multiuploader?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/friendsofredaxo.github.io#73]
**Abstimmung benötigt!**

Bei FOR befindet sich bereits das AddOn [Multiupload](https://github.com/FriendsOfREDAXO/multiupload), das von Hirbod als Lead gepflegt wird. Es ist zu etwa 80% fertig und funktioniert bis auf Drag & Drop, kommt aktuell aber aufgrund von zu wenig Zeit nur langsam voran. Technisch basiert es auf der JS-Komponente [Fine Uploader](https://fineuploader.com), die einen sehr großen Funktionsumfang hat, den Hirbod auch nutzen möchte. Multiupload wird also ein sehr wichtiges AddOn mit vielen schönen Funktionen.

Ingo hatte schon vorher ein weiteres [Multiupload-AddOn](https://github.com/IngoWinter/jquery_file_upload) entwickelt, das aber nie in Konkurrenz stehen sollte. Es basiert auf einer anderen JS-Komponente [jQuery File Upload](https://blueimp.github.io/jQuery-File-Upload/) und ist mehr oder weniger fertig entwickelt. Es bringt langfristig vermutlich weniger Funktionalität mit als das oben beschriebene AddOn und deckt eher die Basisfunktionalität ab, nämlich Mehrfachupload mit clientseitigem Resize. Ingo würde das AddOn FOR übertragen, hat selbst aber aktuell auch eher wenig Zeit für die Weiterentwicklung.

Frage an alle:
Wollen wir Ingos AddOn zusätzlich bei FOR aufnehmen und damit zwei Multiupload haben — einmal eher Basis, einmal eher Extended-Version —, oder reicht uns ein Multiuploader, und wir wollen nicht zwei AddOns pflegen müssen, deren Themen sich überschneiden?

**Comment by schuer** [comment]
Meine Meinung: Ich würde beide bei FOR anbieten, weil sie durchaus leicht unterschiedlich sind.
Allerdings würde ich Hirbods und Ingos Meinungen dazu besonders gewichten.

**Comment by olien** [comment]
Ich finde zwei Multiuploader nicht schlimm....
Mit dem Medienpool 3.0 kommt ja dann bestimmt noch einer :-)

**Comment by staabm** [comment]
Finde ich auch gut. Es sollte nur klar aus der beschreibung hervorgehen was der unterschied ist

**Comment by schuer** [comment]
@alexplusde schreibt im Slack:

> Langfristig vereinen. Falls  unterschiedliche vendoren: als Plugin lösen.

**Comment by joachimdoerr** [comment]
Es gibt ja auch mehrere Editor Addons. Ich sehe das eher unkritisch mit 2 Addons.

**Comment by Hirbod** [comment]
Ich sehe es ebenfalls unkritisch, wobei ich noch erwähnen möchte, dass meine finale Version alle Funktionen von Ingos AddOn abdeckt. Einige Ideen stammen ja von Ingo direkt (z.B. Clientseitiges resizen)

**Comment by darwin26** [comment]
Ich würde es auch nicht verkehrt finden, mehrere zu haben ... solange die Basis-Funktionailtät gleich ist (uploaden von Bilder per Drag&Drop + ggf. vorab resizen).... was das ein oder andere dann noch mehr kann ist halt dann +Feature ... und da die AddOns vermutlich auf Basis eines OpenSource Script aufgebaut sind, wird es sich vermutlich eh iwann splitten, welcher dann den Vorzug hat (stichwort: weiterentwicklung) ...

**Comment by tyrant88** [comment]
+1 für mehrere. 
Langfristig muss es dann in den Medienpool.

**Comment by schuer** [comment]
Okay, das scheint ja recht eindeutig: Ingos Multiuploader soll also zu FOR.
@IngoWinter machst du ihn dann übertragen. Und vielleicht sollten wir uns noch einen anderen AddOn-Key überlegen? Mit `jquery-file-upload` können vermutlich nicht viele was anfangen.

**Comment by schuer** [comment]
Mein Favorit wäre `uploader`. Und falls schon belegt, `file-upload` als Alternative.

**Comment by schuer** [comment]
AddON wurde an FOR übertragen, danke Ingo. Hier geht’s weiter: FriendsOfREDAXO/jquery_file_upload#1

**Comment by staabm** [comment]
Da es 2 gibt finde ich den spezifischen namen ganz gut
