### ISSUE TITLE
AddOn: Website Manager (Port R4, RexDude)

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/friendsofredaxo.github.io#75]
In Slack kam in der Diskussion mit @schuer und Kristof auf, ob ein Port des Website-Managers interessant / relevant wäre - und ob sich Leute finden, diesen für FOR zu portieren.

Addon für R4: https://github.com/RexDude/website_manager 
Diskussion zum R4-Addon im Forum: https://redaxo.org/forum/addons-r4-f30/website-manager-multidomain-addon-fuer-rex-4-5-t19151.html
Lizenz R4: MIT https://github.com/RexDude/website_manager/blob/master/LICENSE.md 

Ich hatte das Addon nie produktiv im Einsatz, der gewählte Ansatz ist jedoch interessant für viele gleichartige Websites in einer Installation (bspw. Ferienhäuser, unterschiedliche Produktseiten) und löst typische Multidomain-Probleme in Redaxo (getrennte Medienpool-Ordner und -Strukturen, Addons sehen auf Wunsch immer nur die gerade gewählte Website)

Hier das passende Issue zum Abschuss freigegeben.

**Comment by schuer** [comment]
Ping @rexdude, vielleicht hast du ja Lust, mit unserer Hilfe den Port zu entwickeln. Du weißt von allen am besten um den Aufbau und hast die Erfahrung, wo (zumindest in R4) die komplizierten Stellen sind. Und wir haben bei FOR die Erfahrung gemacht, wie gut die gemeinsame Entwicklung funktionieren kann, und wir möchten dich gerne motivieren!
