### ISSUE TITLE
Neues FOR-Logo festlegen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/friendsofredaxo.github.io#76]
Hey,

wir hatten die Diskussion neulich im Slack ohne Ergebnis, und weil wir aber handeln müssen, gibt es nun dieses Issue. **Ziel ist, innerhalb der nächsten Woche das neue Logo festzulegen.** Welches es sein soll, können wir gerne diskutieren, am Ende müssen wir jedoch eine Lösung finden, denn das aktuelle Logo kann nicht weiter verwendet werden.

**Vorschlag:** Wenn keine bessere Lösung gefunden wird, nehmen wir den neuen Dino, den Yakamara hat anfertigen lassen. Er entspricht sehr stark dem aktuellen Dino, wurde jedoch von einem Illustrator neu gezeichnet. Ich habe die Entwürfe leider nicht vorliegen, vielleicht kann @dergel sie dem Issue hinzufügen.

Es gab rechtliche Bedenken, dass der neue Dino zu nah am alten liege. Ich persönlich denke, wenn Yakamara als Auftraggeber keine Bedenken hat, brauchen wir als Community auch keine zu haben. Denn wie gesagt: Er ist das Ergebnis eines Gestaltungsauftrags. Vielen Dank nochmal dafür, Yakamara!

Sollten manche von euch wirklich ernsthaft Bedenken haben und sich diese auch nicht ausräumen lassen, schlage ich vor, dass wir eine Anwältin oder einen Anwalt dazu befragen, um sicher zu gehen.

Abschließend nochmal zum Thema Geschmack: Das neue Logo wird nicht jedem gefallen, das ist immer so. Aber bedenkt bitte, dass wir eine Lösung brauchen. Der alte Dino kam damals auch irgendwie ins Projekt, ohne dass darüber diskutiert wurde. Wenn also niemand einen besseren Vorschlag hat, sollte der neue Dino vielleicht auch einfach ins Projekt kommen, ohne dass wir uns darüber totdiskutieren.

Wir können uns gerne für ein anderes Logo entscheiden, aber bitte innerhalb der nächsten Woche, damit das Thema abgehakt werden kann. Okay?

**Comment by schuer** [comment]
Ich pinge mal ein paar Leute, die in der Slack-Diskussion aktiv waren und/oder mit dem Thema zu tun haben, damit sie diese hier nicht verpassen: @skerbis @alexplusde @staabm @elricco @polarpixel @tbaddade @gharlan @IngoWinter @IngoWinter @joachimdoerr @olien @marcohanke @tyrant88 

_(Falls ich jemanden verpasst habe: Sorry, keine Absicht.)_

**Comment by skerbis** [comment]
@schuer mittlerweile habe ich das Original gesehen, das sich farblich  und auch gestalterisch tatsächlich SEHR stark vom neuen Dino unterscheidet, von mir aus kann der neue Dino rein.

**Comment by olien** [comment]
Ich finde den neuen Dino klasse!

**Comment by tyrant88** [comment]
Ich hatte ja meinen Maßstab schon im Slack genannt.
Der alte Dino transportierte gewisse Werte die mir gefielen, der neue tut das nicht.
Leider kann ich es nicht selbst umsetzen, wenn sich also keiner findet, der es macht: me->ignore

**Comment by staabm** [comment]
ich sehe es wie @tyrant88

**Comment by skerbis** [comment]
Tatsache ist, dass der alte verschwinden muss. Da wir aktuell nichts anderes haben, sollten wir den neuen nehmen. Später, wenn Ruhe in die Sache gekommen ist, können sich die Illustratoren ja noch mal austoben.

**Comment by tbaddade** [comment]
Der Dino wurde in der Zwischenzeit nochmals angepasst. So hat dieser nicht mehr allzu viele Kacheln, bekam einen dritten Backenzahn und wurde auf drei Farben reduziert. 
Im Bild noch nicht zu erkennen ist der zweite Schneidezahn vorne links sowie die Reinzeichnung (die feinen Linien zwischen den Kacheln werden noch verschwinden).

![redaxo-friends-logo_v4](https://user-images.githubusercontent.com/338267/32652907-3e681f16-c606-11e7-943f-d6c06349bd7c.png)

Mir persönlich gefällt jetzt diese Variante.

**Comment by schuer** [comment]
Danke fürs Hinzufügen, @tbaddade!

Ich persönlich mag den Dino auch sehr. Die ersten Varianten aus dem Slack fand ich irgendwie besser (nur ein Bauchgefühl), aber das ist schnuppe. Die beiden runden Logos sind cool.

**Comment by skerbis** [comment]
Kriegen wir das heute noch hin?

**Comment by schuer** [comment]
@skerbis Ich würde lieber allen wie im ersten Post angekündigt noch bis nächste Woche Zeit geben, sich zu dem Thema äußern zu können. (just my 2 cents)

**Comment by elricco** [comment]
Also ich finde den neuen Dino ok. Und wir können den auch gerne erstmal einfügen / austauschen finde ich.

**Comment by marcohanke** [comment]
Ich bin kein Polygonfreund, aber die aktuelle Version hat schon auch was vom Charme des alten Dinos. Ich käme mit klar ;-)

**Comment by marcohanke** [comment]
Aber bitte bitte das Friends of nicht so unleserlich …!

**Comment by joachimdoerr** [comment]
Ich war ja schon von anfangen dafür -> Thanks @dergel für den tollen Dino! 
Ggf. FOR mit der Redaxo-Logo Font schreiben ohne Kachelhintergrund.

**Comment by alexplusde** [comment]
Finde die überarbeitete Fassung besser als vorher, aber noch nicht am Ziel:
* Der Kontrast der einzelnen Polygone ist zwar immer noch sehr hoch, wofür ich nach wie vor keine gestalterische Notwendigkeit sehe, aber ok.
* Ein Wechsel der Schrift, die noch dazu die Buchstaben invers setzt, ist gestalterisch nicht begründbar - das ist "REDAXO - komplex - starr - unsinnig" und transportiert damit immer noch nicht die Werte dieser Community.

Als ganz stümperhaftes Beispiel:
![image](https://user-images.githubusercontent.com/3855487/32660742-4e9516fa-c624-11e7-9e63-040e2d21002d.png)

Gleicher Dino, andere Wirkung.

**Comment by IngoWinter** [comment]
Ich bin ebenfalls kein Freund der Polygone und der invertierten Buchstaben. Aber eigentlich ist es mir auch ziemlich Latte - ich würd auch weiter Repos forken wenn wir nen pinken Nacktmull als Maskottchen hätten...

**Comment by dergel** [comment]
obwohl es mit latte ist, finde ich den letzten dino-taler mit blauem untergrund am besten :)

**Comment by tyrant88** [comment]
![b_wk_euucaajhyw](https://user-images.githubusercontent.com/1277494/32662303-52344c26-c62a-11e7-895c-32b86f0c0219.jpg)

**Comment by tyrant88** [comment]
Ernsthaft: der neue ist schon mal besser.

**Comment by schuer** [comment]
Den Kontrast zwischen den Polygonen könnte man wirklich deutlich reduzieren, da bin ich bei @alexplusde.

**Comment by schuer** [comment]
Also, die Zeit läuft, und das Issue hatte ja die Absicht, den alten Dino zu ersetzen, und das machen wir jetzt. Das soll aber niemanden abhalten, einen besseren Entwurf nachzulegen. Wir können das FOR-Logo jederzeit anpassen und modifizieren. Finde ich sogar ziemlich spannend, zeigt es doch eine kontinuierliche Entwicklung, und das ist etwas, was FOR ausmacht: Leute kommen und gehen, Projekte kommen und gehen, Dinos kommen und gehen, REDAXO bleibt.

**Comment by marcohanke** [comment]
Ja Kontrast raus, Kacheln unter der Schrift weg und ab dafür ;-)

**Comment by schuer** [comment]
Der neue Dino ist am Start. Die Entwürfe liegen im `assets`-Branch des FOR-repos: https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io/tree/assets/v2

(Den alten Dino sollten wir dann vermutlich bei Gelegenheit löschen. Mach’s gut, Kumpel, und danke für all den Fisch!)

**Comment by olien** [comment]
> Macht’s gut, und danke ~~all~~ für den Fisch

:-)
