### ISSUE TITLE
Text für CMS Garden überarbeiten

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/friendsofredaxo.github.io#77]
Der aktuelle Text ist inzwischen etwas in die Jahre gekommen. Wurde noch vor R5-Release geschrieben: http://www.cms-garden.org/de/cms/redaxo

**Comment by schuer** [comment]
Wäre vielleicht ein Thema für die Projektarbeit rund um den REDAXO-Tag.

**Comment by eaCe** [comment]
Ein weiterer Kandidat:

https://www.heise.de/download/product/redaxo-34345

**Comment by alexplusde** [comment]
@eaCe der Autor bei Heise wurde soeben von mir informiert.

**Comment by schuer** [comment]
Für den Text auf CMS Garden beachten: Er wird am Ende auf Deutsch und auf Englisch benötigt. (Ich habe gestern erst gemerkt, dass es auf der Seite einen Sprachumschalter gibt. Rechts oben in der Randspalte.)

**Comment by hexabinaer** [comment]
Oh wie schön, Redaxo hat eine Community, die sich auch Gedanken über Texting und die Außendarstellung macht!

Gestatten, ich bin Meike, Mitglied des Redaktionsteams beim CMS Garden. Hallo Redaxo-Community :-)

Vielleicht sollte ich euch ein wenig Hintergrundinformationen geben: Der CMS Garden ist ein Projekt, in dem FOSS-CMS die Möglichkeit gegeben wird, gemeinschaftlich mit anderen Communities Öffentlichkeitsarbeit zu machen. Dazu haben wir einen gemeinnützigen Verein gegründet. Wir bieten Unterstützung bei der Auswahl des passenden CMS, z. B. im Rahmen von Informationsständen auf Tech-Konferenzen und -Messen. Grundlage dieser Möglichkeit ist Engagement. Alle beteiligten CMS-Communities bringen ehrenamtliche Zeit ein und unterstützen das Fundraising. Redaxo war anfangs dabei, hat sich aber mit dem Commitment schwergetan (keine Namensnennung). 

Wir haben neulich noch darüber gesprochen, ob wir die veralteten CMS-Portraits endlich mal von der Website entfernen. Ich persönlich hatte mich lange dafür stark gemacht, wenigstens über den Platzhalter den jeweiligen Communities noch eine Chance zu geben, sind einzubringen. 

Ich würde mich sehr darüber freuen, wenn Redaxo aus der Community heraus die Präsenz im CMS Garden nochmal aufleben lässt. Aber seid gewarnt: es ist nicht damit getan, einen aktualisierten Text zu liefern. Die anderen CMS bringen neben Fundraising viel Engagement (Zeit) ein und sind aktuell eher mäßig daran interessiert, Öffentlichkeitsarbeit für Projekte mit zu machen, dich sich nicht einbringen. 

Kontaktiert mich gern über redaktion@(domain-siehe-oben) mit der Info, ob wir den Text über Redaxo stilllegen sollen oder ob ihr Engagement aufbringen wollt und könnt (ich weiß, wir sind alle schon sehr mit Contributions für unsere "eigenen" Communities beschäftigt). Richtlinien hier: https://www.cms-garden.org/de/faq-page

**Comment by schuer** [comment]
Hallo @hexabinaer und danke für die ausführliche Info! Jüst am kommenden Wochenende trifft sich die REDAXO-Community (zumindest 60-70 Leute davon) zum [REXCamp in Landshut](https://rexcamp2019.de), und ich werde mal im Chat anregen, das Thema CMS Garden dort anzusprechen.

(Wie du siehst ist dieses Issue aber von 2017, und wenn wir als Community es bis heute nicht geschafft haben, den alten Text beim CMS Garden auf einen aktuellen Stand zu bringen, wird das wohl generell nichts mehr werden. Ich zumindest würde ein Nogger Choc drauf verwetten, dass da nichts mehr kommt.)

Jedenfalls, wir geben dir nächste Woche Bescheid. Danke dir fürs Nachhaken und die Anregung! 🏡

**Comment by hexabinaer** [comment]
Nur nicht die Zuversicht verlieren :-) Sofern ihr in der Community ein paar Leute habt, die sich Öffentlichkeitsarbeit/Marketing auf die Fahnen geschrieben haben und da auch aktiv sind, geht es vor allem um das Verständnis, dass wir als Open-Source-CMS gemeinsam bei gleichem Engagement viel mehr erreichen können. 

Auf jeden Fall ist es ein guter Aufhänger, diejenigen auf Contribution-Optionen aufmerksam zu machen, die sich vielleicht beim Coding für nicht gut genug halten. Viel Erfolg!

**Comment by alexplusde** [comment]
Ich teile Dirks Ansicht und erhöhe den Einsatz um ein Raider. ;)

Es ist schon schwierig genug, die eigenen Projekte innerhalb der Community bearbeitet zu sehen...

**Comment by schuer** [comment]
Für die Mitlesenden: Das Thema wurde innerhalb der REDAXO-Community besprochen, und es fehlt uns an Zeit und Motivation, das Projekt CMS Garden zu unterstützen.

Mail an @hexabinaer ist raus, und wir sagen auch hier nochmal vielen Dank dem CMS Garden für ihr Engagement — Alles Gute euch!
