### ISSUE TITLE
Repos : einheitliche Issue-Labels (Namen und Farbe) verwenden

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/friendsofredaxo.github.io#80]

**Comment by staabm** [comment]
Warum will man das? Was sind die vorteile? Welches problem wird dadurch gelöst?
Woher kommt die idee, gibt es einen konkreten anlass?

**Comment by alexplusde** [comment]
Siehe auch: https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io/issues/83

**Comment by schuer** [comment]
Ist hier noch Abstimmungsbedarf, oder handeln wir das Thema in #83 ab?
Sonst gerne close.

**Comment by schuer** [comment]
Hier kam nichts mehr, deshalb schließe ich mal. Sonst gerne wieder öffnen und voranbringen.
