### ISSUE TITLE
Addon: Google Cloud Vision API / Google Translate API / weitere REST APIs

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/friendsofredaxo.github.io#81]
Ein Addon, das verschiedene Google-APIs anbindet und spannende Anwendungsfälle berücksichtigt, bspw.

**Google Cloud Vision API**
- Automatische Verschlagwortung von Bildern (interessant für barrierefreies Webdesign) 
- Automatische Zuordnung von Orten (vlt. interessant für Fotografen)
- Automatische Vorschläge für das Zuschneiden von Bildern

bspw. per Cronjob, an einem Medienpool-Bild direkt oder per EP-Aufruf beim Hochladen eines Bildes.

**Google Translate API**
- Initiale Übersetzung von Begriffen
- Übersetzung der verschlagworteten Bilder (interessant für barrierefreies Webdesign)
- provisorische Übersetzung des Backends, sofern es noch keine passenden lang-Dateien gibt.

Ideen gäbe es von meiner Seite aus zu genüge. Das Addon könnte als Container fungieren, in der andere FOR-Mitgleder ihre API-Lösungen auf allgemeine Weise zur Verfügung stellen.

Hier mal ein Codeschnippsel, der funktioniert, wenn man einen passenden API-Key und ein Medienpool-Bild hinterlegt:

```
<?php

if(rex::isBackend()) {
        
    $question = '{
        "requests": [
        {
            "image": {
            "source": {
                "imageUri": "'.rex::getServer().'media/BILD.jpg'.'"
            }
            },
            "features": [
            {
                "type": "LANDMARK_DETECTION",
                "maxResults": 1
            },
            {
                "type": "LABEL_DETECTION",
                "maxResults": 10
            }
            ]
        }
        ]
    }';  

    $query = 'https://vision.googleapis.com/v1/images:annotate?key=GOOGLEAPIKEY';
    $curl = curl_init();
    curl_setopt_array($curl,array(CURLOPT_URL => $query, CURLOPT_RETURNTRANSFER => true, CURLOPT_POST => true, CURLOPT_HTTPHEADER => array('Content-Type: application/json'), CURLOPT_POSTFIELDS => $question ));
    $resp = curl_exec($curl);

    dump($response = json_decode($resp, true));

    $labels = [];
    foreach($response['responses'][0]['labelAnnotations'] as $annotation) {
        $labels[] = $annotation['description'];
    };

    $question2 = urlencode("This image shows: ".implode(", ", $labels));
    $query2 = 'https://translation.googleapis.com/language/translate/v2?key=GOOGLEAPIKEY&format=text&target=de&q='.$question2;
    $curl2 = curl_init();
    curl_setopt_array($curl2,array(CURLOPT_URL => $query2, CURLOPT_RETURNTRANSFER => true ));
    $resp2 = curl_exec($curl2);

    dump(json_decode($resp2, true));
        
}
```

Ergebnis

![image](https://user-images.githubusercontent.com/3855487/35064324-ea77fd82-fbc9-11e7-86ac-9171a729dd8f.png)

**Comment by elpschulzo** [comment]
Sehr coole Idee und beschränkt auf den MedienPool (als Initialzündung) vielleicht gar nicht mal so wahnsinnig aufwändig.
