### ISSUE TITLE
Addon: Duplikat-Erkennung für Medienpool-Inhalte

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/friendsofredaxo.github.io#82]
Bei den Projekten, die wir auch (inhaltlich) warten, wo aber auch Kunden-MAs ihre Finger im Spiel haben, kommt es häufig vor, das Bilder mehrfach (Rekord: 8) hochgeladen werden. Aktuell prüft das CMS nur auf doppelte Dateinamen und benennt das Duplikat einfach um.

Was helfen würde, wäre ein Addon mit folgenden **Features**:

1. Beim Klick in die Addon-Pages sollte es einen Punkt geben, der den ganzen MP durchleiert, die Medien in einer DB Table hasht und anschließend direkt den Check macht, wo es potentielle oder reale Duplikate gibt. Sobald die Table mind. 1 mal initial befüllt wurde (und danach s.u. möglichst aktuell gehalten wird) kann man in einem weiteren Menüpunkt die Duplikatserkennung für den gesamten Medienpool starten. Man sollte dort sehen, welche Datei die erste war (nach Datum), welche danach als Duplikate reinkamen und wo jeweils all diese Files in Benutzung sind. Unbenutzte Duplikate haben direkt den "Löschen"-Button in Reichweite.

2. Neben dem Hash sind weitere Indikatoren heranzuziehen, je nach Setup: Dateiname, Dateigröße, Dateityp (...).

3. In den Settings sollte einstellbar sein, wie strikt die Prüfung passieren soll (nur Filename, nur Hash, Hash + Filename (und/oder Dateigröße und/oder Typ).

4. Auch einstellbar sein sollte, was im Fall eines Uploads/Syncs passieren soll: nur Meldung ausgeben, restlicher Prozess wie bisher _ODER_ Warnung mit Handlungsaufforderung (Ignorieren + Upload verwerfen) _ODER_ mit Fehler/Warn-Meldung direkt den Upload ausbremsen. 

5. Durch Nutzung der entsprechenden Extension Points ist die Hash Table möglichst aktuell zu halten (Änderungen am MP, Bearbeiten, Löschen, Sync, Upload ...)

----

**Future Plans:**

- Erkennung von "Ähnlichkeit" speziell bei Bildern
- Perfekt wäre, wenn man für die 3 Behandlungsfälle (siehe oben Punkt 4) Profiles an Rollen oder zumindest Admins/Nicht-Admins koppeln könnte (Szenario: Admin darf auch ignorieren, Redakteur nicht)

**Comment by tbaddade** [comment]
Idee finde ich gut, sehe das aber eher direkt im **Medienpool 3.0**

**Comment by elpschulzo** [comment]
Das wäre natürlich noch besser @tbaddade  :+1:

**Comment by staabm** [comment]
ich vermute es wäre rel. einfach... man müsste nach/vorm upload z.b. mit `md5_file()` oder `sha1_file()` den hashwert mit in die media tabelle reinschreiben.

dann kann man vor/nach upload eines weiteren mediums zunächst mittels des hashes prüfen ob es schon exisitiert.

**Comment by IngoWinter** [comment]
bitte aber auch mit der option, diese prüfung komplett auszuschalten. mich persönlich interessierts nicht die bohne, ob ein redakteur medien mehrfach hochlädt.

**Comment by staabm** [comment]
ich denke man würde ihm nur ein hinweis geben dass das identische bild bereits hochgeladen ist.

es ist tendenziell im interesse des betreibers und des hosters ob identische inhalte mehrfach vorhanden sind.

ob man den hinweis selbst abschalten können soll, weiß ich nicht.

**Comment by IngoWinter** [comment]
ich habe unter meinen kunden redakteure/ betreiber, bei denen eine solche funktion supportbedarf weckt. und ich hab lieber ein paar mb mehr im webspace, als den redakteur am telefon. deswegen meine bitte das optional zu mache - developer experience quasi :)

**Comment by alxndr-w** [comment]
Wer dieses Addon möchte, kann ja eins machen. Hier hat sich innerhalb der letzten 5 Jahre (leider) kein zusätzlicher Bedarf gezeigt.
