### ISSUE TITLE
AddOn: Fake Content

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/friendsofredaxo.github.io#87]
Entwicklung eines Addons welches live alle Texte in _Lorem Ipsum_ und alle Bilder in Zufallsbilder oder Platzhalter verwandelt.

So kann eine Webseite auch mal im Entwicklungsstadium gezeigt werden ohne, dass der Content relavant ist.

Inspiration: 

http://www.stevensegallery.com
https://placeholder.com/
https://placeholder.com/text/lorem-ipsum/

**Comment by schuer** [comment]
Gute Idee. Es gibt einige Tools, die dabei unterstützen können. Für PHP etwa https://github.com/fzaninotto/Faker.

**Comment by olien** [comment]
Danke. Das hatte ich schonmal gesehen. Ich dachte eher an irgendetwas was via OutPutFilter die fertige Seite durchgeht ...

**Comment by schuer** [comment]
Achso, du willst gar nicht die Datenbank befüllen, sondern nur temporär beim Seitenaufruf Inhalte einbringen? Stelle ich mir spontan schwierig vor, denn die Inhalte müssen ja jeweils immer an die richtigen Stellen im richtigen Kontext. Die Logik dahinter steckt in Templates und Modulen, vielleicht sogar im JS, und sowas on the fly sinnvoll auszutauschen… keine Ahnung, ob das geht.

**Comment by olien** [comment]
naja. so richtig gut ist es nicht...: http://www.meowbify.com

**Comment by alxndr-w** [comment]
Wer dieses Addon möchte, kann ja eins machen. Hier hat sich innerhalb der letzten 5 Jahre (leider) kein zusätzlicher Bedarf gezeigt.
