### ISSUE TITLE
Addon: Analytics (Google/Piwik)

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/friendsofredaxo.github.io#9]
_From @schuer on May 22, 2016 18:5_

Nur als Idee in den Raum geworfen. Vielleicht hat ja jemand Motivation, sowas umzusetzen:

Wie wäre es mit einem generischen Analytics-Addon, das ein paar schlichte Zahlen im REDAXO-Backend zeigt und Kurven dazu malt? Es müsste auf die APIs der beiden wichtigsten Tracker —  Google und Piwik — zugreifen, und es sollte sicherlich auch in der Lage sein, die Tracking-Codes in verschiedenen Ausführungen in die Website zu injizieren.

Wir haben damals den [Piwik Tracker für R4](https://github.com/skerbis/redaxo_piwik_tracker-rex4) gemacht, der inzwischen von @skerbis gepflegt wird. Sowas in der Art und mit zusätzlichem Support für Google Analytics fände ich klasse. Was meint ihr?

_Copied from original issue: FriendsOfREDAXO/wuensche_ideen#5_

**Comment by schuer** [comment]
_From @polarpixel on May 22, 2016 18:25_

Gute Anregung.
Von @phoebusryan gibt's ja schon das hier:
https://github.com/phoebusryan/rex_analytics

**Comment by schuer** [comment]
_From @phoebusryan on May 23, 2016 6:25_

Das war mal geplant.. ganz kurz aber da GA und Piwik ganz anders funktionieren (das eine ist selfhosted, das andere ist bei google) ... wurde das wieder gecancelt.

https://github.com/phoebusryan/rex_analytics/issues/5
https://github.com/skerbis/redaxo_piwik_tracker-rex4/issues/8

Was es aber wenn irgendwie möglich geben wird, ist eine Ausgabe im Backend für GA:
https://github.com/phoebusryan/rex_analytics/issues/6

**Comment by schuer** [comment]
@phoebusryan Beide haben aber eine API, die angesprochen werden kann, um ein paar Kernzahlen zu holen und ins REDAXO zu malen. Das wäre für mich das Key-Feature, weil danach immer wieder Kund*innen fragen.

Das Einbringen der Tracking-Codes finde ich nett, ginge aber auch von Hand.

**Comment by schuer** [comment]
_From @phoebusryan on May 23, 2016 8:58_

Ja, siehe hier:
https://github.com/phoebusryan/rex_analytics/issues/6

Das wird also definitiv kommen.

**Comment by alexplusde** [comment]
Sehe hier auch Potential für aussagekräftigere Berichte in Richtung SEO / Local SEO mit Daten aus der Search-Console, MyBusiness und einer Wettbewerbsanalyse. Hätte dazu einige Ideen, im Zweifel mal mich in Slack anschreiben - auf gut Glück ausführen werde ich das ohne Interesse erstmal nicht.

**Comment by schuer** [comment]
Danke für die Diskussion. Ich schließe hier mal, okay. Bei Bedarf gerne wieder öffnen.
