### ISSUE TITLE
AddOn: Webmentions

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/friendsofredaxo.github.io#90]
Es gibt gerade diesen schönen Artikel über Webmentions bei ALA: https://alistapart.com/article/webmentions-enabling-better-communication-on-the-internet

Ich bin mir gerade nicht sicher, wie sinnvoll es wäre, sowas in REDAXO zu integrieren, solange es noch keine sinnvolle Blog-Lösung gibt. Andererseits sind Webmentions ja durchaus allgemein nützlich, nicht nur im Umfeld von Blogs.

Jedenfalls: Wäre cool zu sehen, wenn REDAXO bereits Webmentions könnte. Und dann kann man immer noch schauen, was draus wird.

**Comment by georgkaser** [comment]
Tja, die liebe Zeit - wird irgendwie nicht mehr. Wahrscheinlich erst wenn ich den gröbsten Umbau hier im Haus geschafft habe. Wir Österreicher sagen dazu: "Es zaht sich" ;)

Wenn man darüber nachdenkt - sollte man da vielleicht überlegen, wie das dann rechtlich ist? Immerhin hat sich ja mit der DSGVO einiges geändert - und wenn dann jemand via Webmention Dinge auf meiner Seite veröffentlichen kann, wäre das zwar super - aber kann das nicht jetzt auch zu Problemen führen? Muss man das dann auch moderieren?

**Comment by schuer** [comment]
Danke für die Diskussion. Ich schließe hier mal, okay. Bei Bedarf gerne wieder öffnen.
