### ISSUE TITLE
Plugin welches erfolglose Loginversuche speichert 

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/friendsofredaxo.github.io#91]

**Comment by staabm** [comment]
würde es dir aussreichen wenn wir diese info ins syslog schreiben?

**Comment by olien** [comment]
1. Ja. Backend.

2. Mir wäre es egal wo das gespeichert werden würde. Ich habe gerade den Fall, dass ich mich auf einer Webseite nicht mehr anmelden kann weil das PWD geändert wurde. Wenn ich das Passwort ändere um jemanden auszusperren würde es mich schon interessieren ob mit dem Login noch versucht wird sich einzuloggen. Ausserdem fände ich es interessant, ob es evtl "Angriffe" gibt.

3. als Info erwarte ich eigentlich nur Datum/Zeit + Login Name

**Comment by staabm** [comment]
bitte im redaxo core als issue mit diesen infos anlegen. ich denke dass kann man dort einfach einbauen und brauch kein extra plugin.

**Comment by olien** [comment]
https://github.com/redaxo/redaxo/issues/1969
