### ISSUE TITLE
AddOn: Einstieg in REDAXO

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/friendsofredaxo.github.io#92]
Mir ist durch den Kopf gegangen, ob es nicht sinnvoll wäre, ein AddOn zu entwickeln, dass den Einstieg in REDAXO auf verschiedenen Ebenen (Anwendung, Entwicklung, Community, u.a.) vereinfacht. Am liebsten _interaktiv_, also über Möglichkeiten, Themen zu selektieren oder zu filtern und ggfls abzuhaken (im Sinne von: grünes Häkchen), was schon bekannt ist.

Im einfachsten Fall ist es ein reines Info-AddOn, das im Backend verschiedene Tabs zeigt, unter denen Inhalte hängen wie z. B.

* Website-Demos mit Screenshots und Erklärungen
* Community-Links wie Slack, Forum, Weltkarte, Twitter, Facebook
* Developer-Links wie GitHub, FOR, Doku, Tricks
* Dienstleister-Links wie Verzeichnis, Referenzen, Lieblinge
* Neuigkeiten
* Einstiege in Themen: Installer für Updates verwenden, Hilfe finden, Fehler melden, usw.

Im Grunde sowas wie die Seite [Ressourcen auf redaxo.org](https://redaxo.org/support/ressourcen/), nur vermutlich noch etwas detaillierter. Und damit gleich die Frage: Warum reicht diese Seite auf redaxo.org nicht aus, sie ist doch prima? Ja klar, das ist sie, aber sie ist nicht Teil des CMS. Ich könnte mir vorstellen, dass man all diese Infos gerne direkt im REDAXO-Backend hätte.

Und jetzt noch weiter getrieben: Mit diesen Infos innerhalb des Backends könnte man viel mehr anstellen als auf redaxo.org:

* Benutzerabhängige Inhalte: Bereits bekannte Themen ausblenden, neue Themen anbringen und Aktionen fördern (z. B. Sternchen bei GitHub vergeben). Vielleicht mit [Gamification](https://de.wikipedia.org/wiki/Gamification)-Aspekt, so dass es für Benutzer interessant sein könnte, mehr und mehr Themen anzuschauen? 🕹
* Einstiegsseiten bei erstmaligem Login anzeigen, so wie z. B. WordPress das nach Major-Update macht, um die neuen Funktionen des Systems vorzustellen.
* Feedback annehmen und verarbeiten.

Ich hoffe, es wird halbwegs verständlich, wo das alles hinführen könnte.

**Comment by olien** [comment]
Die Idee finde ich prima... 

Hier wäre zu überlegen, ob Redakteure auch berücksichtigt werden könnten. 
Module, indiv. Tabellen oder Addons sind nicht allgemein zu beschreiben aber ich denke, dass 99% unserer Webseite Kategorien, Artikel, den Medienpool etc. nutzen...

**Comment by marcohanke** [comment]
Ich könnte mir das als verschiedene "Tutorials/Anleitungen" vorstellen so wie zum Beispiel hier: https://www.fotor.com/
Das ganze dann für verschiedene Bereiche wie Neue Seiten erstellen, Bilder hochladen, etc. ..

**Comment by elpschulzo** [comment]
Ich hatte über einen ähnlichen Aspekt schon nachgedacht. Wenn man sich mit App-Entwicklung beschäftigt und die Guidelines (von Android) für gute UX anschaut, wird an allen Ecken erwähnt, dass ein "First-Start-Guide" immer gut ankommt und wenn möglich implementiert sein sollte.

Sowas würde ja für REDAXO auch gehen. Entweder tatsächlich als Tour durchs CMS mit Highlighting + umfangreiche Tooltips für die aktuelle Sektion oder on-demand (bspw. wenn einer das erste mal auf "System" klickt.

**Was mir dazu einfällt:**
- könnte User-Bereich erweitern, sodass man beim Anlegen neuer BE-Nutzer einen Haken setzen kann, ob derjenige die Tour nach dem ersten Login mitmachen will
- API für AddOns, sodass bei Erstklick auf die AddOn-BE-Page Highlighting + Tooltips genutzt werden können. Im Default-Fall könnte man auch die Help-Page einblenden.
  - richtig cool wäre natürlich, wenn man das API-seitig auch nochmal als Sub-Tour implementieren könnte: bspw. wenn man das erste mal auf "YForm" klickt, man dann alle (installierten) Sektionen kurz vorgestellt bekommt
- Ziel: Handbuch sparen, Einstiegshürden abbauen, Nähe zu Apps und anderen modernen Applikationen schaffen

**Comment by olien** [comment]
Es gab für rex4 mal das Addon "RETTUNGSRING".. Dort wurde mit tooltips(?) zumindest mal erklärt was die einzelenen Elemente so bewirken.. aber ich glaube Du hast einen anderen Ansatz...

**Comment by schuer** [comment]
Wichtig nochmal, weil es im Slack nicht eindeutig rüber kam: Das AddOn soll nicht die Doku ersetzen. Und auch nicht die Tricks oder andere Quellen. Es soll vielmehr bündeln und die Leute leiten, abhängig davon, welche Bedürfnisse sie haben. Es soll motivieren, das System und die Community näher kennenzulernen. Dabei kann es vielleicht technische Möglichkeiten nutzen, die innerhalb des REDAXO-Backends zur Verfügung stehen, und die an anderer Stelle (etwa redaxo.org) nicht vorhanden sind.

**Comment by crydotsnake** [comment]
Ich find deine Idee richtig super!. Mir ist zu dem Thema auch etwas durch denn Kopf gegangen.
Und zwar, das man im Installer von REDAXO gefragt wird ob man eines der beiden offizielen Demos also die Basis Demo oder die Community Demo gleich mit installieren möchte, so das der User direkt los legen kann.

**Comment by javanita** [comment]
Das ist eine sehr gute Idee. Besonders für Einsteiger ist das sicher sehr nützlich. Für Entwickler Beispiele, da hatte ich schon manche Schwierigkeit.
"Bündeln"  - Linksammlung mit Erläuterungen?

**Comment by alexplusde** [comment]
Ich halte die Demos noch für sehr komplex.

**Comment by olien** [comment]
Hm. Ich hatte gehofft, dass die Modulsammlung den Einstieg auch schon erleichtert...

**Comment by marcohanke** [comment]
Das sind für mich zwei paar Schuhe. Die Modulsammlung ist für Entwickler super. Die müssen sich aber schonmal eingearbeitet haben. Die Doku ist für Entwickler und Anwender super, aber auch sehr umfangreich. Für einen ersten Einstieg für Anwender aber auch für Entwickler fände ich so eine geführte Tour sehr cool. Im Idealfall gibt es ein Demopaket zum Downloaden. Ich installiere es, bekomme in der "AnwenderTour" gezeigt wie ich das System nutze. Wenn ich als Entwickler dann angefixt bin klicke ich auf "EntwicklerTour" und bekomme in ein paar kurzen Tooltips noch Templates, Module und Addons gezeigt und kann währenddessen direkt schon damit rumprobieren. Als Entwickler wäre dann der nächste Schritt die Doku und die Modulsammlung. Aber zum allerersten Kontakt finde ich eine Tour sehr cool ...

**Comment by olien** [comment]
Finden jemand von euch ein gutes Beispiel?

**Comment by marcohanke** [comment]
So in der Art:
https://www.fotor.com/de/app.html#/editor

**Comment by olien** [comment]
Das wäre dann so etwas:

http://heelhook.github.io/chardin.js/
http://yckart.github.io/jquery.tour.js/
http://tracelytics.github.io/pageguide/
http://alvaroveliz.github.io/aSimpleTour/#
http://easelinc.github.io/tourist/
https://ryanfunduk.com/jquery-tourbus/

Ist aber nicht so ganz das, was Dirk sich vorstellt...

**Comment by schuer** [comment]
> Ist aber nicht so ganz das, was Dirk sich vorstellt...

Wichtig ist, was sich die Community vorstellt. Aber stimmt, ich persönlich wollte eigentlich eher keine Overlays einbauen, um eine REDAXO-Tour damit zu realisieren. Mir geht’s in erster Linie darum, dass an zentraler Stelle innerhalb des CMS, dort wo unsere Nutzer zum ersten Mal auflaufen, ein paar relevante Infos vorgehalten werden. Und das möglichst den verschiedenen Nutzertypen entsprechend, z. B. Redakteure, Developer oder Sonstige.

Man könnte mit dem AddOn eine Einstiegsseite implementieren, die sich erstmalig für neue Nutzer automatisch zeigt. Und man könnte dort alle möglichen Ressourcen sinnvoll vorhalten: Screencasts (wie den von @dtpop), Links mit Screenshots + Infos zu den verschiedenen Website-Demos und Einstiege in verschiedene Community-Themen wie Slack, Weltkarte, GitHub, usw. usw.

Das war die ursprüngliche Idee. Aber wie gesagt, wichtig ist, was die Community am Ende möchte. Sollte nur eine Anregung sein, und wir können hier in alle Richtungen diskutieren.

**Comment by olien** [comment]
Vielleicht kann an am Anfang zwei Tabs zur Verfügung stellen.
"Entwickler | Anwender". Sind ja wirklich sehr unterschiedliche Zielgruppen.
(Wobei natürlich auch ein Anwender Hilfe im Slack erhält.)

**Comment by javanita** [comment]
daran hatte ich auch gedacht

**Comment by olien** [comment]
Wenn es denn solch ein AddOn mal geben wird wäre es vielleicht möglich bei der REDAXO Installation zu fragen ob das AddOn "Frist Steps" mit installiert werden soll. Ist es Installiert wird es beim ersten Login angezeigt...

**Comment by olien** [comment]
Könnt Ihr Euch das (als Basis) als Addon vorstellen welches unterschiedliche Plugins (Erste Schritte, Erweiterungen, Links (Entwickler, Community), Infos für Redakteure etc.) beinhaltet?

Dann wäre auf Basis eine Doku Plugins der Anfang ja recht schnell gemacht. Der größere Part wären dann ja die Inhalte. Cool wäre es, wenn die Inhalte auch auf github gepflegt werden könnten.

Das Plugin "Infos für Redakteure" sollte individualisierbar sein und nicht bei einem update überschrieben werden - oder. Also evtl. ein "blank" Plugin hinzuzufügen welches individuell  benutzt werden kann?

Optisch und funktional wäre es dann wirklich (zumindest) anfangs wie die Doku zu search_it / yform.

Habt Ihr noch Ideen?

**Comment by schuer** [comment]
Als kleine Abspaltung vom Thema siehe auch #98

**Comment by schuer** [comment]
Danke für die Diskussion. Ich schließe hier mal, okay. Bei Bedarf gerne wieder öffnen.
