### ISSUE TITLE
Addon: Bearbeiten von Bildern / Imagecrop im Medienpool

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/friendsofredaxo.github.io#93]
Gab es schon mal für R4 - fand ich super nützlich. Vielleicht gibt es auch eine aktuellere Bibliothek? Das Handling in R4 im Medienpool fand ich jedenfalls gut. 
https://redaxo.org/download/addons/key_498/

**Comment by olien** [comment]
Focuspoint reicht dir nicht?

Wie wäre es damit:

https://github.com/fengyuanchen/cropper

?

**Comment by schuer** [comment]
Das neue AddOn Cropper (https://github.com/FriendsOfREDAXO/cropper) sollte diese Aufgabe fürs erste Erledigen. Im Zuge des Medienpool 3.0 wird man es vielleicht noch weiter treiben.

Erstmal close, und falls noch weitere Bedarf ist, gerne wieder öffnen. @cukabeka
