### ISSUE TITLE
Archivierte Repositories als Extraliste ausgeben?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/friendsofredaxo.github.io#94]
https://friendsofredaxo.github.io

@schuer Ich weiß nicht ob das möglich wäre, aber man hätte vielleicht gleich einen besseren Überblick, wenn die archivierten Repositories unterhalb der nicht archivierten gelistet werden.

**Comment by schuer** [comment]
Technisch einfach umsetzbar. Ist es denn gewollt, was meinen die Mitlesenden?

(Ich persönlich finde die aktuelle gemischte Liste besser.)

**Comment by schuer** [comment]
Mag noch jemand eine Meinung zum Thema anbringen?

**Comment by schuer** [comment]
Im Slack nachgefragt, dort war das Ergebnis sehr eindeutig 6:1 für eine separate Liste mit archivierten Projekten.

**Comment by tbaddade** [comment]
Danke dir.
