### ISSUE TITLE
Addon: Static Site Generator

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/friendsofredaxo.github.io#96]
Es wäre cool, wenn REDAXO eine statische HMTL Seite ausspucken könnte...

https://wordpress.org/plugins/static-html-output-plugin/
https://de.wordpress.org/plugins/simply-static/
( https://www.hardypress.com )

**Comment by alexplusde** [comment]
Ein Template?

**Comment by olien** [comment]
?

Es wird komplett funktionierendes statisches html ausgespuckt..

**Comment by olien** [comment]
Nun. Das bietet einige Vorteile. Einmal, dass es dir erlaubt REDSXO in einer sicheren Umgebung zu belassen, zu der niemand außer dir Zugang hat. Und zweitens, dass deine statische Website wirklich, wirklich schnell sein wird. So richtig schnell!

**Comment by aeberhard** [comment]
Für kleinere Seiten bei denen sich nicht oft was ändert auf jeden Fall ideal!

**Comment by staabm** [comment]
> Für kleinere Seiten bei denen sich nicht oft was ändert auf jeden Fall ideal!

hätte ich in solchen seiten dann nicht nur einen static-site-generator? wozu brauch man die kombination mit redaxo?

**Comment by olien** [comment]
ich habe keinen  static-site-generator... den hätte ich ja dann mit redaxo :-))
ich kann mir schon vorstellen, dass ich kleinere seiten mit redaxo baue und dann statisch ausliefere...

**Comment by staabm** [comment]
ok, du willst also nicht einen anderen static site generator in redaxo einbinden, sondern du willst ein addon bauen, dass ein static site generator ist, verstehe.

wäre es nicht sinnvoll wenn das so in die richtung gehen würde, wie die redaxo-doku: man hat irgendwelche markdown files (ob die jetzt auf github liegen, oder direkt in der redaxo instanz, ist ja erstmal egal)?

**Comment by olien** [comment]
@staabm Hm. Eigentlich sollöte ne fertige Seite gespeichert werden.
@schuer Ja. Mir ist klar, dass das nicht mit dynamischen Daten geht. Ist eher für "statische" Seiten gedacht. Ähnlich wie so ein Tool, welches einfach ne Webseite so speichert wie Sie ausgeliefert (wie z.B.: https://ricks-apps.com/osx/sitesucker/index.html)

War nur so eine Idee als ich die WordPress Plugins gesehen habe.

**Comment by nilskoppelmann** [comment]
Statamic hat beispielsweise so einen Static Site Generator (statamic/ssg). Ich würde einbringen, falls es weiterhin Bestreben in dieser Richtung gibt.

**Comment by olien** [comment]
Also wir haben schon so einige Webseiten wo sich sehr, sehr selten bis nie etwas ändert. Wenn REDAXO die uf dem Server in einem Ordner "static" werden könnte hätte ich das beste aus zwei Welten :-) Die Domain zeigt dann einfach auf diesen Ordner. oder? @georgkaser ? (https://www.georgkaser.com/leistungen/webdesign-und-webentwicklung/entwicklung-statischer-websites/)

**Comment by georgkaser** [comment]
Ja, ich verwende dafür allerdings Lektor (https://www.getlektor.com/) - sehr zu empfehlen.

**Comment by aeberhard** [comment]
Für R4 hatte ich da mal ein Addon https://github.com/aeberhard/_realcache_

Schnappt sich die Ausgabe (OUTPUT_FILTER) und schreibt das komplette HTML in ein Cache-Verzeichnis.
Beim nächsten Aufruf wird direkt dieses HTML ausgespuckt. Geschwindigkeit wie bei statischen Seiten.
Bei Änderungen im Backend wurde das Cache-File gelöscht. und noch a bisserl mehr glaube ich :)

Für Seiten die selten geändert werden auf jeden Fall ein Performance-Boost.

**Comment by alxndr-w** [comment]
[https://github.com/aeberhard/_realcache_](https://github.com/aeberhard/_realcache_) GitHub hat deinen Link zerhauen

**Comment by aeberhard** [comment]
Ah, Danke Alex!

**Comment by skerbis** [comment]
https://github.com/akrys/redaxo-exportproject

**Comment by alxndr-w** [comment]
Unter Windows kann man httrack bemühen. Das kann dann auch URLs passend umschreiben. Sobald irgendwas dynamisches kommt, ist der Ansatz hinfällig. 

Allenfalls wenn rewriting im Spiel wäre, wenn der Server selbständig erstmal versucht, die Adresse aufzulösen. Dann müsste es die Möglichkeit geben, bei jeder Artikel-Änderung eine HTML-Datei abzulegen und an jedem Artikel sagen zu können, ob er statisch oder dynamisch sein soll.

Also ziemlich viel redaktioneller Aufwand für die paar Millisekunden.

**Comment by olien** [comment]
Es geht hier ja nicht um Millisekunden sondern darum eine statische Seite erzeugen zu können. Nicht umsonst gibt es inzwischen viele Systeme die darauf ausgelegt sind genau das zu tun. Hier ist auch ein Umweg über eine Desktop-Software sicherlich nicht praktikabel. Wenn es REDAXO nicht kann (war ja nie vorgesehen und dafür ist es ja auch nicht gebaut) ist es halt so. Dachte nur, dass es evtl. "einfach" geht und es wäre manchmal sicherlich ein gutes Verkaufsargument :-)

**Comment by skerbis** [comment]
In meinem Fall ist es die Sicherung eines Intranets (YCOM), damit man nach einer Katastrophe (z.B. totaler Netzausfall) noch an die Daten gelangt.

**Comment by tbaddade** [comment]
Indexiert searchit nicht das Frontend und speichert den Inhalt in der DB ab? 

Eventuell das AddOn aufbohren, dass der komplette Artikel zusätzlich als Datei abgelegt wird.

**Comment by skerbis** [comment]
@tbaddade soweit ich weiss macht searchIt es ohne Templates

**Comment by tyrant88** [comment]
@alxndr-w Es ist doch nicht die Aufgabe eines Caches Inhalte jederzeit offline bereit zustellen.

**Comment by alxndr-w** [comment]
> @alxndr-w Es ist doch nicht die Aufgabe eines Caches Inhalte jederzeit offline bereit zustellen.

https://entwickler.de/programmierung/offlinemodus-die-achillesferse-der-progressive-web-apps

Sorry, meinte über PWA und Service Worker

**Comment by tyrant88** [comment]
Erhöhter Einsatz beim Buzzword Poker? ;-) ;-) ;-)

**Comment by tbaddade** [comment]
> > Eventuell das AddOn aufbohren, dass der komplette Artikel zusätzlich als Datei abgelegt wird.

> @tbaddade soweit mir bekannt ist, macht searchIt es ohne Templates

@skerbis deshalb ja das AddOn erweitern, dass der komplette Artikel gespeichert wird :)

**Comment by alxndr-w** [comment]
Wer dieses Addon möchte, kann ja eins machen. Hier hat sich innerhalb der letzten 5 Jahre (leider) kein zusätzlicher Bedarf gezeigt.
