### ISSUE TITLE
Addon: Payment

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/friendsofredaxo.github.io#97]
Ein Addon, das Zahldienste wie PayPal-Plus-APIs registriert, und eine kurze Anleitung zeigt, wie man bspw. auf den Kauf eines Items über ein simples YForm-Formular
- den Kauf in der Datenbank protokolliert
- E-Mails über YForm E-Mail-Templates an Käufer und Händler übermittelt
- den Käufer zur Bezahlung weiterleitet und die dafür nötigen Credentials, Token, Datensatz-IDs bereitstellt
- nach Abschluss des Kaufs Parameter entgegen nimmt und ggf. weitere Mails an Käufer und Händler versendet.
- bei nicht erfolgreicher Bezahlung weitere Instruktionen auslöst
- Die Bezahlung oder den Fehlerfall in der Datenbank protokolliert und den Kaufdatensatz updatet.

**Comment by alexplusde** [comment]
* Sandboxing sollte unterstützt sein.

**Comment by joachimdoerr** [comment]
https://github.com/thephpleague/omnipay

**Comment by elpschulzo** [comment]
Ich habe da Erfahrung aus einem Kunden-Testcase mit Concardis. Die haben ne API, bilden PayPal, Kreditkarte, SÜ etc. ab.
Im Backend zur API kann man Hooks registrieren, die JSON an eine angegebene URL schicken können (je nach Änderung des Status zur Bestellung erfolgt ein Request). Das lenkt man dann auf ne Zielseite, die den Kram verarbeitet und in ne YForm Table packt. Kann man gut auch für Gutscheine und so Kram nutzen und klappt soweit echt easy.

Ich weiß halt nicht, ob man bei so guten Lösungen am Markt noch was eigenes bauen muss. Größter Pluspunkt wäre natürlich, dass keine Dritten die Hand auf halten, aber selbst kann man ja keine Kreditkarten- oder Rechnungszahlungen sinnvoll abbilden (verifizieren, durchführen, stornieren...). Vielleicht wäre ein AddOn/Modul eine Idee, wo man sich vorher einen Zahlungsdienstleister sucht, der für alle REDAXO-Pages und das dann verwendete AddOn besondere Konditionen bietet. Nur so ne Idee...

**Comment by alexplusde** [comment]
Es ist schon so gemeint, dass das Add-on ein oder mehrere sdks zur Installation bereitstellt und Mustercode liefert.
