### ISSUE TITLE
AddOn: Support REDAXO!

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/friendsofredaxo.github.io#98]
Abspaltung von #92. Dort hat es sich in eine Richtung Doku/Tipps/Tutorials entwickelt, die sicherlich auch spannend ist, aber mir schwebt aktuell lediglich ein einzelner Teil davon als AddOn vor: **Wie kann man innerhalb des REDAXO-Backends Nutzer dazu bringen, das System und die Community zu unterstützen.**

Es sollte eine Art Checklist-Charakter haben, und es sollten kleine Ansätze von Gamification enthalten sein, so dass seitens der Nutzer die Motivation aufkommt, die Checklist zu durchlaufen. Sehr nett macht das diese Website, bei der es inhaltlich um Security-Theme geht: https://securitycheckli.st

<img width="834" alt="screenshot 2019-01-15 17 44 32" src="https://user-images.githubusercontent.com/1297466/51195639-cd2b6600-18ed-11e9-83df-fd5bfa34f276.png">

Für REDAXO könnte ich mir diverse typische Items auf der Checkliste vorstellen, die dem System und seiner Community nützlich wären, etwa:

- GitHub-Sterne vergeben, um die Sichtbarkeit zu erhöhen
- Auf Twitter folgen, um in Aktivitäten involviert zu werden
- Einen REDAXO-Tag besuchen
- Den Slack besuchen, um mit anderen zu diskutieren
- Sich auf der Community-Map eintragen, um die Sichtbarkeit der Community zu stärken
- FOR-Mitglied werden
- Einen Text für die Doku schreiben oder einen Fehler korrigieren

Es gibt sicherlich weitere, mal mehr oder weniger aufwendig, mal mehr oder weniger technisch ausgerichtet, mal mehr oder weniger Community-orientiert.

Der (sehr gering ausgeprägte) Gamification-Faktor liegt darin, dass für jede angehakte Aktion Punkte vergeben werden — vielleicht unterschiedlich viele, je nachdem wie aufwendig oder hilfreich eine Aktion ist — und dass diese Punkte im Nutzeraccount der REDAXO-Installation hinterlegt werden, so dass man mit anderen REDAXO-Nutzern vergleichen könnte. Und dann geht es halt schlicht darum: Wie viele Punkte kann ich erreichen, und wer hat die meisten Punkte.

Jedenfalls: Das wäre die Idee, und sie ist technisch und inhaltlich sehr einfach umzusetzen, wenn man sie so ähnlich macht wie die oben verlinkte Security-Checkliste. Was meint ihr? Und wie würdet ihr das AddOn nennen?

**Comment by staabm** [comment]
in symfony gibts ein "thanks" bundle, mit dem man sterne vergibt (via github api automatisiert), an alle bundles die man verwendet (also in der aktuellen anwendung installiert sind):

https://github.com/symfony/thanks

**Comment by staabm** [comment]
weitere idee: man könnte es auch "love" nennen. macht vllt dann auch ein bissl neugierig.

**Comment by schuer** [comment]
Coole Idee, @staabm!

**Comment by gharlan** [comment]
Bei Symfony kann man Badges sammeln.
Bei mir sind es noch nicht viele: https://connect.symfony.com/profile/gharlan
Bei Fabien hingegen schon: https://connect.symfony.com/profile/fabpot ;)

Man bekommt Badges für (Liste unvollständig):
- X Jahre dabei sein
- Contributions zu X
- An Konferenz X teilgenommen

Finde ich vom Prinzip ganz nett.

**Comment by tbaddade** [comment]
> weitere idee:

T-Rex >> **rooar**, **rrrrr**

**Comment by schuer** [comment]
Die Sache mit den Badges und dem sf-thanks finde ich prima, erfordert nur etwas mehr Aufwand an verschiedenen Stellen. MyREDAXO-Accounts pimpen und so weiter.

Vielleicht macht man erstmal nur das AddOn, um zu starten? Das besteht ja nur aus Info und verhältnismäßig wenig Programmieraufwand für Frontend und Backend.

**Comment by gharlan** [comment]
Jupp sehe ich auch so. Wollte es nur mal zeigen, aber das große Fass würde ich jetzt auch eher nicht aufmachen.

**Comment by TobiasKrais** [comment]
Würde ich nicht machen. Meine Methode Redaxo zu pushen ist teure Addons wie d2u_immo kostenlos zur Verfügung zu stellen. So generieren wir einen Mehrwert für Leute die sich für ein CMS entscheiden.

**Comment by schuer** [comment]
> Ich würde es nicht benutzen. Weder als Anfänger, noch als Fortgeschrittener. #my2cents

@alexplusde Voll okay, muss nicht jedem passen. Danke für dein Feedback!

> Würde ich nicht machen. Meine Methode Redaxo zu pushen ist teure Addons wie d2u_immo kostenlos zur Verfügung zu stellen. So generieren wir einen Mehrwert für Leute die sich für ein CMS entscheiden.

@TobiasKrais »Würde ich nicht machen.« im Sinne von nicht benutzen oder nicht das AddOn entwickeln? Deine Variante, tolle AddOns zur Verfügung zu stellen, ist natürlich viel nachhaltiger, als eine Checkliste anzubieten. Dennoch denke ich, dass man ruhig vielfältig sein kann, und dass es die Community bereichert, wenn Leute unterschiedliche Ideen, Ansätze und Motivation haben. Mir persönlich würde so eine Checkliste z. B. gefallen, und ich würde hoffen, dass sie manchen Leute dazu verhilft, überhaupt erst zu erkennen, wie sie die Community unterstützen können. Warum es etwa hilfreich ist, bei GitHub Sterne zu vergeben, warum ein Eintrag auf der Map die Sichtbarkeit der Community erhöht, dass es einen Slack gibt und es sich lohnt, dort vielleicht mal reinzuschauen, und so weiter.

**Comment by alexplusde** [comment]
@schuer nach Abschluss des Setups wäre imho der richtige Ort für einen Teil deiner Ideen. Dann nimmt's im Backend keinen Platz weg.

Vielleicht noch so als konstruktiver Beitrag meinerseits :)

**Comment by TobiasKrais** [comment]
@schuer grundsätzlich fördert das Redaxo und der Vorschlag macht daher auch Sinn. Trotzdem die Antwort auf deine Frage: Ich würde es nicht benutzen und auch nicht als Addon entwickeln. Wenn ich meine Kunden / Redaxo Nutzer anschaue, würde das Feature niemand benutzen. Z.B. hat keiner ein GitHub Konto.
Daher denke ich, dass Nutzer nicht die Adressaten sind. Vielleicht noch Administratoren. Das würde in die Richtung gehen, die @alexplusde vorschlägt. Aber will ich den Hinweis in allen Intallationen eingeblendet haben? Eher nicht. Weniger ist mehr.

**Comment by staabm** [comment]
Um die informationen zu bekommen die dirk vorschlägt wäre auch kein github account nötig. Die infos wären im backend von redaxo, wenn ich es richtig verstehe

**Comment by schuer** [comment]
> nach Abschluss des Setups wäre imho der richtige Ort für einen Teil deiner Ideen. Dann nimmt's im Backend keinen Platz weg.

@alexplusde Ich vermute ja eher, nach dem Setup hat man als Nutzer einen anderen Fokus, als irgendwelche GitHub-Sternchen zu vergeben; womöglich noch für ein System, dass man gerade erstmalig entdeckt.

> Daher denke ich, dass Nutzer nicht die Adressaten sind. Vielleicht noch Administratoren.

@TobiasKrais Man hört doch oft von begeisterten REDAXO-Nutzern. Vielleicht brauchen die Anregungen, wie sie das System unterstützen können. ¯\\\_(ツ)_/¯ 

> Um die informationen zu bekommen die dirk vorschlägt wäre auch kein github account nötig. Die infos wären im backend von redaxo, wenn ich es richtig verstehe.

Ja, GitHub-Sterne vergeben ist nur eine Option von vielen. Nicht alle passen für alle Nutzertypen, aber dennoch wird sicherlich für alle was dabei sein. Die coolste Option passt für alle: Einen REDAXO-Tag besuchen. :)

**Comment by schuer** [comment]
Danke für die Diskussion. Ich schließe hier mal, okay. Bei Bedarf gerne wieder öffnen.
